import { learningLesson } from "@/lib/content/helpers";
import type { Course, Lesson, LessonBlock } from "@/lib/types";
import { createPlannedVoiceVariants, DEFAULT_VOICE_ID } from "@/lib/narration";

interface FeatLessonConfig {
  slug: string;
  title: string;
  description: string;
  concept: string;
  explanation: string;
  task: string[];
  objective: string;
  sourceSection: string;
  command?: string;
  expected?: { output: string; explanation: string };
  image?: { src: string; alt: string; caption: string };
  qc?: string;
  troubleshooting?: { title: string; body: string; command?: string };
}

const configs: FeatLessonConfig[] = [
  {
    slug: "what-first-level-means",
    title: "What first-level analysis means",
    description: "Connect one participant's BOLD time series to a model of one run.",
    objective: "Distinguish first-level analysis from within-subject and group analysis",
    concept: "First-level analysis models a single run from a single participant. It estimates how well the predicted response for each explanatory variable accounts for the observed BOLD signal at every voxel.",
    explanation: "The output is not a group conclusion. It is a set of participant/run-specific parameter estimates and contrasts that can later feed Level 2 or Level 3 models. Keep the unit of analysis explicit when naming outputs.",
    task: ["Choose one BOLD run in a BIDS dataset.", "Identify its participant, task, and run entities.", "Sketch where its first-level .feat output should live."],
    sourceSection: "Learning objectives and folder structure",
  },
  {
    slug: "what-is-a-glm",
    title: "What is a GLM?",
    description: "Understand the model that relates expected task responses and confounds to the BOLD signal.",
    objective: "Explain the response, predictors, parameter estimates, and residuals in an fMRI GLM",
    concept: "The general linear model represents the measured BOLD time series as a weighted combination of explanatory variables plus unexplained residual error. FEAT fits this model separately at each voxel while accounting for temporal structure.",
    explanation: "The design matrix contains one row per time point and columns for task predictors and nuisance regressors. Parameter estimates describe each column's contribution. A good-looking activation map cannot rescue a design matrix that does not represent the experiment.",
    task: ["Write the model as Y = Xβ + ε.", "Label Y, X, β, and ε in plain language.", "Name one task predictor and one nuisance predictor for your study."],
    expected: { output: "Y = Xβ + ε", explanation: "Y is observed BOLD signal, X is the design matrix, β contains parameter estimates, and ε contains residual error." },
    sourceSection: "Stats tab — EVs and contrasts",
  },
  {
    slug: "experimental-timing-files",
    title: "Experimental timing files",
    description: "Translate BIDS events into FSL's onset, duration, and amplitude format.",
    objective: "Create and validate a three-column FSL timing file",
    concept: "An FSL three-column timing file has one event per row: onset in seconds, duration in seconds, and amplitude. Each condition normally has its own file.",
    explanation: "Timing is relative to the start of the modeled run. Units, missing events, and condition labels must be checked against the BIDS events.tsv file. A syntactically valid file can still encode the wrong experiment.",
    task: ["Open a matching events.tsv file.", "Choose one condition.", "Create a three-column text file.", "Check that onsets are within the run duration."],
    command: "awk 'NR==1 || $3==\"choice\" {print}' sub-001_task-choice_events.tsv\nhead choice.txt",
    expected: { output: "12.000  1.500  1\n28.250  1.500  1", explanation: "Each row describes when an event began, how long it lasted, and its amplitude." },
    sourceSection: "Create 3-column timing files",
  },
  {
    slug: "what-is-an-ev",
    title: "What is an explanatory variable?",
    description: "Represent one hypothesized source of signal as a column in the design matrix.",
    objective: "Distinguish original EVs from convolved predictors and nuisance regressors",
    concept: "An explanatory variable (EV) represents a pattern expected to explain some variation in the data. Task events, parametric values, motion estimates, and other confounds can all become EVs, but their interpretations differ.",
    explanation: "FEAT begins with the event timing you specify, convolves task EVs with a hemodynamic response, and may add temporal derivatives. Each resulting column consumes model degrees of freedom, so include predictors for a reason—not simply because they are available.",
    task: ["List the experimental conditions in one run.", "Decide which need separate EVs.", "List motion or confound regressors separately.", "State what a positive parameter estimate would mean for one EV."],
    sourceSection: "Stats tab — EV setup",
  },
  {
    slug: "hrf-and-convolution",
    title: "The HRF and convolution",
    description: "Turn event timing into a prediction of the delayed BOLD response.",
    objective: "Explain why neural event timing is convolved with a hemodynamic response function",
    concept: "The hemodynamic response function (HRF) approximates the delayed, smooth BOLD response that follows brief neural activity. Convolution combines event timing with this response shape to create a model predictor.",
    explanation: "The predictor should resemble the signal you expect to measure, not an instantaneous event list. FEAT offers basis choices and temporal derivatives, but extra flexibility changes the model and interpretation. Use the course or study protocol rather than defaulting blindly.",
    task: ["Draw a brief event at 10 seconds.", "Sketch a delayed response peaking several seconds later.", "Compare your sketch with FEAT's plotted EV shape."],
    sourceSection: "Stats tab — convolution settings",
  },
  {
    slug: "confound-regressors",
    title: "Confound regressors",
    description: "Model nuisance variation without treating it as the effect of interest.",
    objective: "Explain why and how nuisance regressors enter a first-level design",
    concept: "Confound regressors capture structured variation—such as motion—that is not the experimental effect of interest. They reduce bias when specified appropriately, but they do not automatically repair poor data.",
    explanation: "Motion estimates, non-steady-state volumes, physiological terms, or fMRIPrep confounds may be used according to a documented strategy. Check column count, missing values, and time points. A confound file must have one row per modeled volume.",
    task: ["Find the number of BOLD volumes.", "Count rows and columns in the confound file.", "Confirm there are no text headers if FEAT expects numeric input.", "Document why each column is included."],
    command: "fslval filtered_func_data.nii.gz dim4\nwc -l confounds.txt\nhead confounds.txt",
    expected: { output: "240\n240 confounds.txt", explanation: "The BOLD series and confound file have the same number of time points." },
    sourceSection: "Supplement — extract basic confounds",
  },
  {
    slug: "understanding-contrasts",
    title: "Understanding contrasts",
    description: "Turn parameter estimates into a focused hypothesis test.",
    objective: "Write and interpret contrast weights for common task hypotheses",
    concept: "A contrast specifies the hypothesis you want to test by assigning weights to one or more EV parameter estimates. The weights define a linear combination; they do not change the original model fit.",
    explanation: "With EVs [Faces, Places], [1, 0] tests Faces relative to the implicit baseline, while [1, -1] tests Faces greater than Places. The order must match the design matrix. Name contrasts in scientific language and verify every row visually.",
    task: ["Write EVs in matrix order.", "Create weights for condition A, condition B, A > B, and B > A.", "State the null hypothesis for A > B."],
    expected: { output: "A: [1 0]\nB: [0 1]\nA > B: [1 -1]\nB > A: [-1 1]", explanation: "Each row combines the two EV estimates in the order they appear in the model." },
    image: { src: "/curriculum/feat-contrasts.png", alt: "FEAT contrast manager showing contrast weights", caption: "A real FEAT contrast configuration from the adapted source lab." },
    qc: "Match every contrast column to the displayed EV name. A correct set of numbers in the wrong order tests a different hypothesis.",
    sourceSection: "Contrasts",
  },
  {
    slug: "opening-feat",
    title: "Opening FEAT",
    description: "Start the correct analysis mode and understand FEAT's tabs.",
    objective: "Open a first-level FEAT analysis and identify the role of each configuration tab",
    concept: "FEAT is both a model-configuration interface and a pipeline runner. Its tabs organize inputs, preprocessing, registration, statistics, and thresholded reporting.",
    explanation: "Select First-level analysis and Full analysis only when the workflow calls for both preprocessing and statistics. If using already preprocessed data, settings must reflect that choice. Never assume the GUI remembers a safe configuration from a previous session.",
    task: ["Open an FSL terminal.", "Launch FEAT.", "Select First-level analysis.", "Read each tab without changing values and note which tabs are enabled."],
    command: "Feat &",
    sourceSection: "Open FEAT",
  },
  {
    slug: "configuring-data-tab",
    title: "Configuring the Data tab",
    description: "Set the number of inputs, repetition time, input file, and output directory.",
    objective: "Configure and verify the core Data-tab inputs",
    concept: "The Data tab establishes the time-series input and output identity for the model. The TR and number of volumes determine how model timing aligns to measured data.",
    explanation: "Choose the 4D BOLD input—not a mean image or JSON file. Give the output a new, descriptive name. FEAT appends `.feat`; avoid an existing directory unless intentionally resuming or replacing work.",
    task: ["Select the BOLD input.", "Verify its dim4 and TR against fslinfo and JSON metadata.", "Choose a non-existing output path.", "Record the final output name in your notes."],
    command: "fslval sub-001_task-choice_bold.nii.gz dim4\nfslval sub-001_task-choice_bold.nii.gz pixdim4",
    expected: { output: "240\n2.000000", explanation: "This example has 240 volumes and a 2-second TR; enter values that match your own run." },
    sourceSection: "Data tab (inputs and outputs)",
  },
  {
    slug: "configuring-preprocessing",
    title: "Configuring preprocessing options",
    description: "Make preprocessing choices that match the actual state of the input data.",
    objective: "Relate FEAT Pre-stats settings to prior preprocessing",
    concept: "Preprocessing settings are scientific decisions about motion correction, brain extraction, smoothing, and temporal filtering. Applying a step twice is not neutral.",
    explanation: "For raw data, follow the validated course workflow. For fMRIPrep-preprocessed input, disable steps already performed and handle registration deliberately. Inspect the source data and provenance before selecting options.",
    task: ["Classify the input as raw or preprocessed.", "Create a checklist of completed preprocessing operations.", "Configure FEAT to avoid unintended duplication.", "Save the design before running."],
    image: { src: "/curriculum/feat-prestats.png", alt: "FEAT Pre-stats tab showing motion correction, brain extraction, smoothing, and filtering controls", caption: "The FEAT Pre-stats controls used in the source lab." },
    qc: "Open the raw BOLD series before running FEAT. Look for missing coverage, severe motion, spikes, and orientation problems.",
    sourceSection: "Pre-stats tab",
  },
  {
    slug: "creating-evs",
    title: "Creating EVs",
    description: "Add condition timing, convolution, derivatives, and naming in matrix order.",
    objective: "Configure task EVs from validated timing files",
    concept: "Each EV connects a scientific condition to a predictor column. Its name, timing file, convolution, and derivative settings jointly determine what the model estimates.",
    explanation: "Use meaningful names and keep a written EV order. Preview timing files before loading them. If the same condition never occurs in a run, decide how that run should be modeled before launching FEAT.",
    task: ["Set the number of original EVs.", "Name each EV.", "Load its three-column timing file.", "Choose the protocol-specified convolution.", "Inspect the EV plot."],
    command: "for f in timing/*.txt; do echo \"$f\"; head -3 \"$f\"; done",
    sourceSection: "Stats tab — EV setup",
  },
  {
    slug: "creating-contrasts",
    title: "Creating contrasts",
    description: "Encode planned hypothesis tests and verify them against EV order.",
    objective: "Configure named contrasts and F-tests where scientifically justified",
    concept: "Contrasts operate on estimated EV effects. A t-contrast tests one weighted direction; an F-test can ask whether any contrast in a selected set explains variance without specifying one direction.",
    explanation: "Create contrasts from the preregistered or approved analysis plan. Include directional opposites only when they answer planned questions. The contrast manager is the final place to catch swapped columns.",
    task: ["Open the contrast manager.", "Name each contrast with its scientific interpretation.", "Enter weights in EV order.", "Use the design preview to confirm the rows."],
    image: { src: "/curriculum/feat-stats.png", alt: "FEAT Stats tab used to configure the model and contrasts", caption: "The FEAT Stats workflow adapted from Lab 3." },
    qc: "Read each contrast as a sentence while pointing to its EV columns. If the sentence and weights differ, stop and correct the model.",
    sourceSection: "Contrasts",
  },
  {
    slug: "inspecting-design-matrix",
    title: "Inspecting the design matrix",
    description: "Check timing, collinearity, EV shape, and contrast order before spending compute time.",
    objective: "Perform a pre-run design-matrix quality-control review",
    concept: "The design matrix is the model in visual form. Column shapes reveal timing and convolution; correlations reveal whether predictors may be difficult to estimate separately.",
    explanation: "Confirm that task predictors occur when expected, nuisance columns have plausible structure, and contrasts select the intended columns. Strong correlations are not automatically errors, but they affect what the model can distinguish.",
    task: ["Click View design.", "Match each column to an EV.", "Look for empty or duplicated columns.", "Review the correlation report.", "Match every contrast arrow to the intended columns."],
    qc: "Do not run FEAT until the design matrix tells the same experimental story as the protocol and timing files.",
    sourceSection: "Stats and design matrix QC",
  },
  {
    slug: "running-feat",
    title: "Running FEAT",
    description: "Save the design, launch the model, and monitor it without confusing silence for failure.",
    objective: "Run a first-level design and identify signs of progress or failure",
    concept: "FEAT saves configuration to an `.fsf` file and generates a `.feat` directory containing logs, intermediate data, model estimates, registration, and an HTML report.",
    explanation: "Before running, save the design and record the output path. Use logs and process checks when the interface is quiet. Do not launch a second copy simply because a long registration or model-fitting step produces little output.",
    task: ["Save the .fsf design.", "Select Go.", "Locate the new .feat directory.", "Open report_log.html or the log files and identify the current stage."],
    command: "find . -maxdepth 2 -type d -name '*.feat'\nfind first_model.feat -maxdepth 2 -type f -name '*log*' | sort",
    troubleshooting: { title: "FEAT will not proceed", body: "Check timing-file format, contrast configuration, missing inputs, and output-name conflicts. Read the first explicit error rather than only the final failure message.", command: "ls -lah timing/\ntail -50 first_model.feat/report_log.html" },
    sourceSection: "Run first-level statistics",
  },
  {
    slug: "feat-directory",
    title: "Understanding the .feat directory",
    description: "Navigate FEAT outputs without treating every NIfTI as a final result.",
    objective: "Locate design, registration, filtered data, statistics, and report files",
    concept: "A `.feat` directory is a structured analysis record. It contains the copied design, processed time series, registration transforms, statistical estimates, thresholded maps, logs, and linked reports.",
    explanation: "`design.fsf`, `design.mat`, `design.con`, and `design.png` describe the model. `stats/` contains estimates and statistics. `reg/` contains registration products. The HTML report is an entry point—not a substitute for understanding the files.",
    task: ["List the top level of a .feat directory.", "Find design files and the stats directory.", "Locate the report and registration images.", "Write one sentence describing each group."],
    command: "find first_model.feat -maxdepth 2 -type f | sort | sed -n '1,80p'",
    sourceSection: "Viewing and QC'ing FEAT output",
  },
  {
    slug: "cope-versus-z-statistic",
    title: "PE, cope, varcope, t-statistic, and z-statistic",
    description: "Separate effect estimates, uncertainty, standardized evidence, and thresholded displays.",
    objective: "Explain what each major first-level statistical output represents",
    concept: "A PE estimates one EV coefficient. A cope is a contrast of PEs. A varcope estimates the cope's variance. A t-statistic standardizes the cope by its uncertainty; FEAT converts it to a z-statistic for inference and reporting.",
    explanation: "A larger z-statistic can result from a larger estimated effect, lower uncertainty, or both. The cope retains effect scale and is the quantity passed with its varcope into higher-level models. Do not describe a z-statistic map as an effect-size map.",
    task: ["Open stats/cope1 and stats/zstat1 in FSLEyes.", "Compare their numerical ranges.", "Open stats/varcope1.", "Explain why the maps answer different questions."],
    command: "fslstats first_model.feat/stats/cope1 -R\nfslstats first_model.feat/stats/varcope1 -R\nfslstats first_model.feat/stats/zstat1 -R",
    expected: { output: "cope: estimated contrast effect\nvarcope: uncertainty of that effect\nzstat: standardized evidence", explanation: "The exact numeric ranges vary; the interpretation of each output does not." },
    sourceSection: "Stats output interpretation",
  },
  {
    slug: "inspecting-registration",
    title: "Inspecting registration",
    description: "Verify functional-to-anatomical and anatomical-to-standard alignment across the brain.",
    objective: "Carry out a visual registration quality-control check",
    concept: "Registration estimates spatial mappings between functional, anatomical, and standard images. A completed transform file only means an optimization finished, not that alignment is anatomically credible.",
    explanation: "Use the FEAT registration report and FSLEyes overlays. Inspect cortical boundaries, ventricles, cerebellum, and multiple slices. Watch for gross shifts, scaling errors, flips, missing coverage, or distortions.",
    task: ["Open the Registration section of the FEAT report.", "Inspect all available boundary images.", "Load registered outputs over the reference in FSLEyes.", "Record pass, concern, or fail with a reason."],
    qc: "Do not assume successful registration because FEAT completed. Open the registered images and visually compare anatomical boundaries.",
    sourceSection: "Viewing output — Registration",
  },
  {
    slug: "interpreting-feat-report",
    title: "Interpreting the FEAT report",
    description: "Read the report as a linked quality-control narrative from input to inference.",
    objective: "Review Pre-stats, Registration, Stats, and Post-stats evidence in order",
    concept: "The FEAT report organizes evidence about preprocessing, model design, registration, and statistical thresholding. Each page answers a different question about the validity of the run.",
    explanation: "Start with motion and preprocessing plots, then registration, then the design matrix and contrasts, and only then thresholded results. Bright clusters are not meaningful if earlier QC fails.",
    task: ["Open report.html.", "Review Pre-stats before Post-stats.", "Write one QC statement for motion, registration, and design.", "Open one result image in FSLEyes."],
    image: { src: "/curriculum/feat-report.png", alt: "A FEAT HTML report showing analysis results and navigation", caption: "A real FEAT report captured in the source curriculum." },
    sourceSection: "Viewing and QC'ing FEAT output",
  },
  {
    slug: "common-level-one-failures",
    title: "Common Level 1 failures",
    description: "Diagnose missing tabs, incorrect outputs, timing problems, and registration surprises.",
    objective: "Use a reproducible triage order for common FEAT failures",
    concept: "Effective troubleshooting starts with environment, location, existence, format, and logs. Changing many settings at once destroys the evidence needed to identify a cause.",
    explanation: "Confirm the correct terminal and directory, check each input path, validate timing rows and contrast setup, inspect output naming, then read the report log. A blank Post-stats tab often indicates that Stats mode or contrasts are not configured as expected.",
    task: ["Choose one failed or practice model.", "Record pwd and FSL availability.", "Check input and timing paths.", "Read the earliest failing command in the log.", "Change one cause and rerun to a new output."],
    command: "pwd\nwhich feat\nls -lh input_bold.nii.gz timing/*.txt\nfind . -name report_log.html -print",
    troubleshooting: { title: "Structural image looks unstripped", body: "First inspect the BET output directly, then verify that FEAT points to the intended structural image and that the registration method's required inputs are present.", command: "fsleyes sub-001_T1w.nii.gz sub-001_T1w_brain.nii.gz &" },
    sourceSection: "FEAT troubleshooting",
  },
  {
    slug: "complete-guided-analysis",
    title: "Complete guided analysis",
    description: "Build, run, inspect, and explain a full first-level model from one example run.",
    objective: "Complete the first-level workflow with an auditable QC record",
    concept: "A complete analysis is more than a `.feat` directory. It includes validated inputs, an interpretable model, documented decisions, successful computation, and explicit quality-control observations.",
    explanation: "Use the sequence-pilot or OpenNeuro example from the source lab. Create timing files, configure FEAT, inspect the design before running, review every report section, then explain one cope and z-statistic in plain language.",
    task: ["Validate the BOLD run and events.", "Build timing files and the FEAT design.", "Complete design-matrix QC.", "Run to a new output directory.", "Review motion, registration, model, and thresholded results.", "Mark this lesson complete only after writing a short QC summary."],
    command: "feat first_model.fsf",
    qc: "Your final note must include evidence for input quality, model validity, registration, and results—not only whether FEAT finished.",
    sourceSection: "Complete ds000157 exercise",
  },
];

function createFeatLesson(config: FeatLessonConfig, index: number): Lesson {
  const lesson = learningLesson({
    id: `first-level-${config.slug}`,
    slug: config.slug,
    number: `${index + 1}.1`,
    title: config.title,
    description: config.description,
    duration: index === 19 ? 45 : 22,
    objectives: [config.objective, "Connect the concept to a concrete FEAT or Neurodesk check"],
    conceptTitle: config.title,
    concept: config.concept,
    explanation: config.explanation,
    task: config.task,
    command: config.command,
    expected: config.expected,
    selfCheck: {
      question: `In one or two sentences, what decision does “${config.title}” support?`,
      answer: config.objective,
    },
    summary: [config.description, "Document the decision and inspect the corresponding input or output."],
    sourceLab: config.slug === "confound-regressors" ? "Lab-3_Supplement.md" : "Lab-3_FSL_Level1.md",
    sourceSection: config.sourceSection,
    videoType: index >= 7 ? "walkthrough" : "concept",
    videoTitle: index >= 7 ? `${config.title} in FEAT` : config.title,
    image: config.image,
    troubleshooting: config.troubleshooting,
    callout: config.qc ? { variant: "quality-control", title: "Quality Control Check", body: config.qc } : undefined,
  });

  if (config.slug === "complete-guided-analysis") {
    const secondVideo: LessonBlock = {
      type: "video",
      videoType: "quality-control",
      title: "Reviewing a complete FEAT report",
      provider: "mux",
      videoId: null,
      durationMinutes: 11,
      status: "planned",
      captionsPath: "/production/captions/reviewing-feat-report.vtt",
      defaultVoiceId: DEFAULT_VOICE_ID,
      voiceVariants: createPlannedVoiceVariants("reviewing-complete-feat-report"),
      transcript: "A reviewed transcript will appear when the quality-control video is published.",
    };
    lesson.blocks.splice(3, 0, secondVideo);
  }
  return lesson;
}

export const firstLevelCourse: Course = {
  id: "course-first-level",
  slug: "first-level-fmri-analysis-feat",
  catalogNumber: "FSL 301",
  title: "First-Level fMRI Analysis in FEAT",
  shortTitle: "First-Level FEAT",
  description:
    "Move from experimental timing to an interpretable first-level model, then inspect FEAT outputs with the care expected in graduate research.",
  difficulty: "Intermediate",
  status: "available",
  duration: "8 weeks · 10 hours",
  prerequisites: ["FSL & Neuroimaging Foundations", "Basic understanding of task-based fMRI", "A working Neurodesk FSL environment"],
  objectives: [
    "Explain the voxelwise general linear model and hemodynamic convolution",
    "Prepare event timing and confound regressors",
    "Configure EVs, contrasts, preprocessing, and registration in FEAT",
    "Interpret PE, cope, varcope, t-statistic, and z-statistic outputs",
    "Review a FEAT report and document scientific quality control",
  ],
  requirements: ["Desktop or laptop", "FSL in Neurodesk or an institutional cluster", "Example BIDS dataset from the source lab"],
  neurodeskRequired: true,
  accent: "amber",
  sourceLabs: ["Lab-3_FSL_Level1.md", "Lab-3_Supplement.md", "Lab-X_Contrast.md", "Lab-0_GeneralTroubleshootingGuide.md"],
  resources: [
    {
      id: "timing-files",
      title: "Example timing files",
      description: "FSL three-column format for the guided model.",
      format: "TXT bundle",
      href: "#",
      available: false,
    },
    {
      id: "source-level1",
      title: "Original Level 1 lab",
      description: "The MIT-licensed TUBRIC walkthrough adapted for this course.",
      format: "Markdown",
      href: "https://github.com/tubric/2026s-fmri-class/blob/main/Lab-3_FSL_Level1.md",
      available: true,
    },
  ],
  modules: configs.map((config, index) => ({
    id: `first-level-module-${index + 1}`,
    number: index + 1,
    title: config.title,
    description: config.description,
    lessons: [createFeatLesson(config, index)],
  })),
};
