import { learningLesson } from "@/lib/content/helpers";
import type { Course } from "@/lib/types";

export const foundationsCourse: Course = {
  id: "course-foundations",
  slug: "fsl-neuroimaging-foundations",
  catalogNumber: "FSL 101",
  title: "FSL & Neuroimaging Foundations",
  shortTitle: "FSL Foundations",
  description:
    "Build the practical vocabulary and terminal confidence you need to inspect neuroimaging data with FSL, FSLEyes, and Neurodesk.",
  difficulty: "Beginner",
  status: "available",
  duration: "5 weeks · 7 hours",
  prerequisites: ["No FSL experience required", "No prior Linux experience required"],
  objectives: [
    "Explain how FSL and Neurodesk fit into an fMRI workflow",
    "Navigate Linux folders and verify files from the terminal",
    "Distinguish 3D and 4D NIfTI images and read essential metadata",
    "Inspect anatomy, functional time series, overlays, and coordinates in FSLEyes",
    "Use core FSL utilities and interpret their output",
  ],
  requirements: ["Desktop or laptop recommended for practical work", "Modern browser", "Neurodesk Play, EDU, or institutional FSL access"],
  neurodeskRequired: true,
  accent: "mint",
  sourceLabs: ["Lab-0_Neurodesk.md", "Lab-0_Glossary.md", "Lab-1_FSLeyes.md", "Lab-0_GeneralTroubleshootingGuide.md"],
  resources: [
    {
      id: "foundations-cheatsheet",
      title: "Linux & FSL command sheet",
      description: "A compact reference for the terminal commands used in this course.",
      format: "PDF",
      size: "Coming soon",
      href: "#",
      available: false,
    },
    {
      id: "source-lab-1",
      title: "Original FSLEyes lab",
      description: "The MIT-licensed TUBRIC laboratory material adapted for this course.",
      format: "Markdown",
      href: "https://github.com/tubric/2026s-fmri-class/blob/main/Lab-1_FSLeyes.md",
      available: true,
    },
  ],
  modules: [
    {
      id: "foundations-welcome",
      number: 1,
      title: "Welcome to FSL",
      description: "Understand the toolchain and prepare a reliable working environment.",
      lessons: [
        learningLesson({
          id: "foundations-what-is-fsl",
          slug: "what-is-fsl",
          number: "1.1",
          title: "What is FSL?",
          description: "Meet the collection of tools used to inspect, preprocess, model, and report MRI data.",
          duration: 16,
          objectives: ["Describe FSL as a suite rather than one application", "Match common FSL tools to their purpose"],
          conceptTitle: "FSL is a toolkit, not a single program",
          concept:
            "FSL—the FMRIB Software Library—is a collection of command-line tools and graphical interfaces for MRI analysis. FEAT handles fMRI modeling, FSLEyes displays images, and utilities such as fslinfo, fslstats, and fslmaths inspect or transform data.",
          explanation:
            "A typical workflow moves between tools. You might inspect a raw BOLD image in FSLEyes, configure a model in FEAT, run it, then return to FSLEyes to check registration and statistical maps. Learning FSL therefore means learning both the scientific purpose of each step and the output it produces.",
          task: ["Open Neurodesk in a second window.", "Locate the FSL application tile.", "Open an FSL terminal and identify the version shown in the prompt."],
          command: "which fslinfo\nfslinfo --version 2>/dev/null || echo \"FSL is available\"",
          expected: {
            output: "/usr/local/fsl/bin/fslinfo",
            explanation: "A returned path confirms that the terminal can find FSL. The exact path varies by Neurodesk version.",
          },
          selfCheck: {
            question: "Why do we move between FEAT, FSLEyes, and FSL utilities?",
            answer: "They serve different roles: model configuration, visual inspection, and command-line measurement or transformation.",
          },
          summary: ["FSL is a suite of related neuroimaging tools.", "Successful computation never replaces visual quality control."],
          sourceLab: "Lab-0_Glossary.md",
          sourceSection: "FSL, FSLEyes, and fslstats",
          callout: {
            variant: "note",
            title: "Educational scope",
            body: "These lessons teach transferable workflows. Always follow the preprocessing and statistical protocol approved for your project or institution.",
          },
        }),
        learningLesson({
          id: "foundations-course-workflow",
          slug: "how-this-course-works",
          number: "1.2",
          title: "How this course works",
          description: "Use each lesson as a two-window study session: explanation here, analysis in Neurodesk.",
          objectives: ["Set up an effective two-window workspace", "Use expected output as a check rather than an answer key"],
          conceptTitle: "Understand, observe, reproduce",
          concept:
            "Each workflow is split into a concept, a real interface walkthrough, an independent Neurodesk task, and an output check. The point is not to memorize button positions; it is to understand what information enters and leaves each step.",
          explanation:
            "Pause often. Predict what a command or FEAT setting will do before you run it. Then compare the result with the expected output and explain discrepancies in your own words.",
          task: ["Place this lesson on one side of your screen.", "Place Neurodesk on the other side.", "Create a notes file for observations and unresolved questions."],
          selfCheck: {
            question: "When should you look at expected output?",
            answer: "After making a prediction and running the step yourself, so the comparison tests understanding rather than copying.",
          },
          summary: ["Predict before running a step.", "Record what you observe, especially when it differs from the example."],
          sourceLab: "Lab-0_Neurodesk.md",
          sourceSection: "Recommended options and setup",
          callout: {
            variant: "desktop",
            title: "Practical labs work best on a computer",
            body: "Videos and reading work on mobile, but use a desktop or laptop for Neurodesk exercises and side-by-side quality control.",
          },
        }),
        learningLesson({
          id: "foundations-neurodesk",
          slug: "getting-started-with-neurodesk",
          number: "1.3",
          title: "Getting started with Neurodesk",
          description: "Choose Play, EDU, or an institutional environment and verify that FSL is available.",
          duration: 25,
          objectives: ["Choose an appropriate Neurodesk access route", "Distinguish a base terminal from an FSL terminal", "Choose persistent storage"],
          conceptTitle: "A reproducible software environment",
          concept:
            "Neurodesk packages neuroimaging applications in consistent environments. Neurodesk Play is broadly accessible; Neurodesk EDU may be provided by a course or institution; a local installation is optional and has higher hardware requirements.",
          explanation:
            "Files saved only inside temporary browser sessions may disappear. Use the persistent storage location provided by your environment. The base terminal is useful for general Linux work; an FSL terminal starts with the FSL software environment already loaded.",
          image: {
            src: "/curriculum/neurodesk-launch.png",
            alt: "Neurodesk launcher showing the option to open a local Neurodesk session",
            caption: "The local launcher shown in the source lab. Browser-based Play and EDU sessions have a similar app workspace.",
          },
          task: ["Launch Neurodesk Play, EDU, or your institution's environment.", "Open the FSL application.", "Open its terminal and verify FSL with which fslinfo.", "Identify the location where your files persist between sessions."],
          command: "which fslinfo\npwd\necho $SHELL",
          expected: {
            output: "/usr/local/fsl/bin/fslinfo\n/home/jovyan\n/bin/bash",
            explanation: "Your exact paths may differ. You need a valid fslinfo path and a known persistent working location.",
          },
          troubleshooting: {
            title: "FSL command not found?",
            body: "You may be in the base terminal rather than the FSL application terminal. Open the FSL tile, or load the FSL module if your environment supports modules.",
            command: "ml fsl\nwhich fslinfo",
          },
          selfCheck: {
            question: "What is the operational difference between the base terminal and an FSL terminal?",
            answer: "The FSL terminal has the FSL environment loaded; the base terminal is a general shell and may not find FSL commands until a module is loaded.",
          },
          summary: ["Know which terminal you are using.", "Save work in persistent storage.", "Verify tools before starting a long analysis."],
          sourceLab: "Lab-0_Neurodesk.md",
          sourceSection: "Browser setup and FSL terminal",
        }),
      ],
    },
    {
      id: "foundations-linux",
      number: 2,
      title: "Linux essentials",
      description: "Navigate deliberately and diagnose path problems before they derail an analysis.",
      lessons: [
        learningLesson({
          id: "foundations-terminal",
          slug: "the-terminal",
          number: "2.1",
          title: "The terminal",
          description: "Read a shell prompt and understand commands, options, and arguments.",
          objectives: ["Identify a command and its arguments", "Use built-in help safely"],
          conceptTitle: "Commands are precise instructions",
          concept:
            "A shell command usually begins with a program name, followed by options and arguments. Spaces separate tokens; capitalization matters; the shell does not guess which file you intended.",
          explanation:
            "In `ls -lh data`, `ls` is the command, `-lh` changes the display, and `data` is the target directory. Reading commands this way makes unfamiliar examples easier to adapt.",
          task: ["Open a base terminal.", "Run the command below.", "Use man ls or ls --help and find the meaning of -h."],
          command: "ls -lh",
          expected: { output: "total 12K\ndrwxr-xr-x 2 jovyan users 4.0K data", explanation: "The exact listing differs. `-l` adds details and `-h` makes sizes human-readable." },
          selfCheck: { question: "What role does `data` play in `ls -lh data`?", answer: "It is the argument—the directory that `ls` should list." },
          summary: ["Commands, options, and arguments are separate tokens.", "Paths and capitalization must be exact."],
          sourceLab: "Lab-0_Glossary.md",
          sourceSection: "Command + arguments + options",
        }),
        learningLesson({
          id: "foundations-navigation",
          slug: "linux-navigation",
          number: "2.2",
          title: "Linux navigation",
          description: "Use pwd, ls, and cd to move through a project without losing track of your location.",
          duration: 24,
          objectives: ["Report the current working directory", "Move between parent and child folders", "Distinguish absolute from relative paths"],
          conceptTitle: "Your working directory is context",
          concept:
            "Relative paths are interpreted from the current working directory. Absolute paths begin at the filesystem root `/`. Many “missing file” errors are really context errors: the file exists, but not where the current command is looking.",
          explanation:
            "Use `pwd` before any command that writes output. Use `ls` to verify the next directory name before `cd`. The shortcuts `.` and `..` mean the current and parent directories, while `~` means your home directory.",
          task: ["Print your current location.", "Create a course practice directory.", "Enter it and create data and output subfolders.", "Return to the parent directory using .."],
          command: "pwd\nmkdir -p fsl-academy-practice/{data,output}\ncd fsl-academy-practice\nls\ncd ..",
          expected: { output: "data  output", explanation: "Brace expansion creates both subfolders. `pwd` should change after `cd` and return after `cd ..`." },
          troubleshooting: { title: "Cannot find a file?", body: "Stop and verify context instead of repeatedly changing the command. Print the directory, list its contents, then search narrowly.", command: "pwd\nls -lah\nfind . -maxdepth 3 -name '*bold*'" },
          selfCheck: { question: "When is `data/sub-001` a valid path?", answer: "When a data directory exists inside the current working directory; otherwise use the correct relative or absolute path." },
          summary: ["Use pwd → ls → cd as a deliberate loop.", "Create output directories before analysis.", "Most path errors are diagnosable with small checks."],
          sourceLab: "Lab-0_GeneralTroubleshootingGuide.md",
          sourceSection: "Linux navigation basics",
        }),
      ],
    },
    {
      id: "foundations-data",
      number: 3,
      title: "Neuroimaging data",
      description: "Build a mental model for voxels, volumes, NIfTI files, metadata, and BIDS folders.",
      lessons: [
        learningLesson({
          id: "foundations-nifti",
          slug: "what-is-a-nifti-image",
          number: "3.1",
          title: "What is a NIfTI image?",
          description: "Interpret the dimensions and spatial metadata stored in .nii and .nii.gz files.",
          duration: 26,
          objectives: ["Differentiate voxels and volumes", "Interpret dim1–dim4", "Relate pixdim4 to repetition time"],
          conceptTitle: "A 4D image is a time-ordered stack of 3D volumes",
          concept:
            "A voxel is a three-dimensional sample. An anatomical NIfTI is usually one 3D volume; a BOLD NIfTI usually contains many volumes along a fourth, temporal dimension. Header metadata records dimensions, voxel sizes, orientation, and timing.",
          explanation:
            "If `dim4` is 240, the BOLD series contains 240 volumes. Spatial resolution comes from `pixdim1` through `pixdim3`; `pixdim4` often records the TR in seconds. Always verify the units in the header and JSON sidecar.",
          task: ["Navigate to a NIfTI file.", "Run fslinfo on it.", "Record dim1–dim4 and pixdim1–pixdim4.", "Decide whether the file is anatomical or functional."],
          command: "fslinfo sub-001_task-choice_bold.nii.gz",
          expected: { output: "dim1 64\ndim2 64\ndim3 40\ndim4 240\npixdim4 2.000000", explanation: "This example is a 64 × 64 × 40 image sampled over 240 time points with a 2-second TR." },
          selfCheck: { question: "What does `dim4 = 240` mean for a BOLD image?", answer: "The file contains 240 three-dimensional volumes in its time series." },
          summary: ["Voxels make up volumes; volumes make up a 4D time series.", "Inspect headers rather than inferring dimensions from filenames."],
          sourceLab: "Lab-0_Glossary.md",
          sourceSection: "NIfTI, voxel, and 3D vs 4D data",
        }),
        learningLesson({
          id: "foundations-bids",
          slug: "understanding-bids",
          number: "3.2",
          title: "Understanding BIDS",
          description: "Read standardized neuroimaging filenames and find anatomy, function, events, and metadata.",
          objectives: ["Identify BIDS entities in a filename", "Locate anatomical and functional inputs", "Explain the role of JSON and events.tsv files"],
          conceptTitle: "Structure is part of the data",
          concept:
            "The Brain Imaging Data Structure (BIDS) uses predictable folders and filenames so people and software can identify participants, sessions, tasks, runs, and modalities without relying on local naming conventions.",
          explanation:
            "A functional run lives under `sub-*/func/` and pairs a `_bold.nii.gz` image with a `_bold.json` sidecar. Its `_events.tsv` file describes event onsets and durations. Anatomical T1-weighted data typically live under `sub-*/anat/`.",
          task: ["List one participant folder.", "Find one BOLD image and its JSON sidecar.", "Find the matching events.tsv file.", "Translate each filename entity into plain language."],
          command: "find sub-001 -maxdepth 2 -type f | sort",
          selfCheck: { question: "Why does a BOLD run need both NIfTI and JSON files?", answer: "The NIfTI stores image data; the JSON sidecar stores acquisition metadata that may not be represented reliably in the image filename or header." },
          summary: ["BIDS makes inputs discoverable and machine-readable.", "Match images, sidecars, and events by their shared entities."],
          sourceLab: "Lab-0_Glossary.md",
          sourceSection: "BIDS and file types",
        }),
      ],
    },
    {
      id: "foundations-fsleyes",
      number: 4,
      title: "Inspecting data in FSLEyes",
      description: "See structure, time, overlays, coordinates, and common quality problems.",
      lessons: [
        learningLesson({
          id: "foundations-fsleyes-intro",
          slug: "introduction-to-fsleyes",
          number: "4.1",
          title: "Introduction to FSLEyes",
          description: "Load anatomical and functional NIfTI files and orient yourself in three planes.",
          duration: 28,
          objectives: ["Open files from the terminal", "Navigate sagittal, coronal, and axial views", "Read voxel and world coordinates"],
          conceptTitle: "Visual inspection is an analysis step",
          concept:
            "FSLEyes lets you examine image geometry and intensity directly. The orthographic view shows the same location in three anatomical planes. The overlay list controls which images are visible and how they are colored.",
          explanation:
            "Start by checking that the brain is oriented sensibly, the field of view is complete, and signal is present. For 4D images, move through volumes or open the time-series view. A file loading without an error does not prove that the data are usable.",
          image: { src: "/curriculum/fsleyes-timeseries.png", alt: "FSLEyes displaying an fMRI volume with the time-series view open", caption: "A real FSLEyes time-series view from the adapted TUBRIC lab." },
          task: ["Launch FSLEyes with a NIfTI path.", "Move the crosshair through the brain.", "Record one scanner coordinate and voxel coordinate.", "For a BOLD file, open View → Time series."],
          command: "fsleyes sub-001/anat/sub-001_T1w.nii.gz &",
          selfCheck: { question: "Why can the same point have both voxel and scanner coordinates?", answer: "Voxel coordinates index the image grid; scanner/world coordinates locate that point in physical space using the image affine." },
          summary: ["Inspect every key input and output visually.", "Use the overlay list and coordinate panel deliberately."],
          sourceLab: "Lab-1_FSLeyes.md",
          sourceSection: "Viewing MRI data and functional time series",
          callout: { variant: "quality-control", title: "Quality Control Check", body: "Confirm orientation, brain coverage, and visible signal before beginning preprocessing. A later pipeline cannot recover anatomy that was never acquired." },
        }),
        learningLesson({
          id: "foundations-overlays",
          slug: "overlays-atlases-and-time-series",
          number: "4.2",
          title: "Overlays, atlases, and time series",
          description: "Compare aligned images, inspect a BOLD signal over time, and use atlas labels as references.",
          objectives: ["Configure overlay opacity and color maps", "Interpret a voxel time series", "Use atlas labels cautiously"],
          conceptTitle: "One coordinate, several sources of evidence",
          concept:
            "Overlays let you compare images in the same coordinate space. Time-series plots show how a voxel changes across volumes. Atlas lookup adds an anatomical label, but atlas boundaries are probabilistic and should not be treated as ground truth for every participant.",
          explanation:
            "Registration QC is easiest when boundaries from two images can be seen together. Alternate visibility, adjust opacity, or use an edge overlay. For functional data, look for sudden spikes, drifts, or dropout and relate them to later motion and preprocessing reports.",
          task: ["Load an anatomical background and a functional or standard-space overlay.", "Reduce overlay opacity.", "Check alignment in at least three distant locations.", "Open atlas tools and note the probability for one label."],
          selfCheck: { question: "Why is a single central slice insufficient for registration QC?", answer: "Misalignment can be local or more visible near boundaries; several planes and regions must be inspected." },
          summary: ["Use overlays to test spatial correspondence.", "Atlas labels are references, not perfect individual anatomy."],
          sourceLab: "Lab-1_FSLeyes.md",
          sourceSection: "Navigating anatomy, functional data, and atlas tools",
          callout: { variant: "quality-control", title: "Quality Control Check", body: "Inspect multiple slices and brain boundaries. Do not accept registration because the images overlap near the center." },
        }),
      ],
    },
    {
      id: "foundations-utilities",
      number: 5,
      title: "FSL command-line basics",
      description: "Measure, transform, and extract data while keeping outputs interpretable.",
      lessons: [
        learningLesson({
          id: "foundations-fslutils",
          slug: "fslinfo-and-fslstats",
          number: "5.1",
          title: "fslinfo and fslstats",
          description: "Inspect image metadata and compute targeted summary statistics.",
          duration: 25,
          objectives: ["Choose fslinfo for metadata", "Use fslstats flags intentionally", "Recognize the importance of masks and thresholds"],
          conceptTitle: "Metadata describes the container; statistics describe its values",
          concept:
            "`fslinfo` reports header fields such as dimensions and voxel sizes. `fslstats` computes statistics over image intensities, optionally after applying thresholds or masks. A number is only interpretable when you know which voxels contributed to it.",
          explanation:
            "For example, `fslstats image -R` reports the robust intensity range. `-V` reports the number and physical volume of nonzero voxels. Nonzero voxels are not automatically the brain; background noise, skull, or artifacts may also be nonzero.",
          task: ["Run fslinfo and record image dimensions.", "Use fslstats -R for the intensity range.", "Use -V and explain both returned numbers.", "Open the image to verify what was counted."],
          command: "fslinfo example_bold.nii.gz\nfslstats example_bold.nii.gz -R\nfslstats example_mask.nii.gz -V",
          expected: { output: "0.000000 14322.000000\n81234 649872.000000", explanation: "For `-V`, the first value is the count of nonzero voxels and the second is their volume in mm³." },
          selfCheck: { question: "Why is `fslstats image -V` not automatically a brain-volume measurement?", answer: "It counts all nonzero voxels, which may include non-brain signal unless the image is a validated brain mask." },
          summary: ["Match the utility to the question.", "Define which voxels a statistic summarizes.", "Check numerical results against the image."],
          sourceLab: "Lab-0_Glossary.md",
          sourceSection: "fslstats and estimating volume",
        }),
        learningLesson({
          id: "foundations-math-meants",
          slug: "fslmaths-and-fslmeants",
          number: "5.2",
          title: "fslmaths and fslmeants",
          description: "Create masks and extract a mean time series without losing track of image space.",
          duration: 27,
          objectives: ["Build a simple thresholded mask", "Extract a masked mean time series", "Verify that mask and data spaces match"],
          conceptTitle: "Transform first, measure second",
          concept:
            "`fslmaths` applies image operations in sequence and writes a new image. `fslmeants` summarizes a 4D time series within a mask. The mask and source data must have compatible dimensions and spatial alignment.",
          explanation:
            "A binary mask contains 1 for included voxels and 0 elsewhere. Thresholding alone may not create a scientifically valid ROI; it is simply an operation. View every derived mask before using it to extract values.",
          task: ["Create a binary mask from an example image.", "Open the mask over the source image.", "Confirm dimensions with fslinfo.", "Extract a mean time series and inspect its first values."],
          command: "fslmaths zstat1.nii.gz -thr 3.1 -bin zstat1_mask.nii.gz\nfslmeants -i filtered_func_data.nii.gz -m zstat1_mask.nii.gz -o mean_signal.txt\nhead mean_signal.txt",
          expected: { output: "98.4213\n99.7731\n101.204", explanation: "One mean value is returned per BOLD volume. Values depend entirely on the data and mask." },
          selfCheck: { question: "What must you verify before using a mask with fslmeants?", answer: "That it is scientifically appropriate and aligned to the same dimensions and space as the 4D input." },
          summary: ["fslmaths writes derived images; preserve meaningful names.", "Never extract a signal from an uninspected mask."],
          sourceLab: "Lab-1_FSLeyes.md",
          sourceSection: "Measuring the brain and atlas masks",
          callout: { variant: "quality-control", title: "Quality Control Check", body: "Overlay the mask on the exact image used for extraction. Matching dimensions do not guarantee meaningful anatomical alignment." },
        }),
      ],
    },
  ],
};
