import type { TroubleshootingArticle } from "@/lib/types";

export const troubleshootingArticles: TroubleshootingArticle[] = [
  { id: "wrong-terminal", category: "Neurodesk", title: "FSL command not found", symptom: "The shell returns “command not found” for feat, fsleyes, or fslinfo.", resolution: "Confirm that you opened the FSL application terminal. In environments with modules, load FSL and verify the executable path before retrying the analysis.", commands: ["ml fsl", "which fslinfo"], tags: ["terminal", "fsl", "path"] },
  { id: "storage-location", category: "Neurodesk", title: "Files disappeared after the session", symptom: "Work saved during a browser session is not present after reconnecting.", resolution: "Use the persistent storage path provided by Neurodesk Play, EDU, or your institution. Record that path at the start of each lab and keep source data separate from derivatives.", commands: ["pwd", "ls -lah"], tags: ["storage", "play", "edu"] },
  { id: "wrong-directory", category: "Linux", title: "Cannot find a file", symptom: "A command reports that an input does not exist even though it was downloaded earlier.", resolution: "Check the current directory, list the expected parent, then search within a narrow project root. Paths and capitalization must match exactly.", commands: ["pwd", "ls -lah", "find . -maxdepth 4 -name '*bold*'"], tags: ["file", "path", "directory"] },
  { id: "output-location", category: "Linux", title: "Cannot find analysis output", symptom: "The program appears to have completed, but the expected output is not in the current folder.", resolution: "Inspect the output path recorded in the design or command. FEAT adds .feat or .gfeat suffixes and may write nested output below a participant directory.", commands: ["find . -maxdepth 5 -type d \( -name '*.feat' -o -name '*.gfeat' \)"], tags: ["output", "feat", "find"] },
  { id: "datalad-placeholder", category: "DataLad", title: "A downloaded filename looks strange", symptom: "FSLEyes shows a git-annex object path or the image content is unavailable.", resolution: "Check whether the path is a symlink, fetch the file content with DataLad, then unlock it only when the exercise requires a regular writable file.", commands: ["ls -l sub-001/anat/sub-001_T1w.nii.gz", "datalad get sub-001/anat/sub-001_T1w.nii.gz", "datalad unlock sub-001/anat/sub-001_T1w.nii.gz"], tags: ["git-annex", "symlink", "download"] },
  { id: "poststats-blank", category: "FEAT", title: "The Post-stats tab is blank", symptom: "Post-stats controls are disabled or the results page contains no contrasts.", resolution: "Verify that the analysis type includes statistics, original EVs are configured, and at least one valid contrast exists. View the design and correct model setup before running again.", commands: ["ls -lh timing/*.txt"], tags: ["post-stats", "contrast", "ev"] },
  { id: "feat-model-fails", category: "FEAT", title: "The model will not run", symptom: "FEAT stops during setup or immediately after launch.", resolution: "Check input existence, three-column timing format, row values within run duration, contrast definitions, and output-name conflicts. Read the earliest explicit error in the FEAT log.", commands: ["fslval input_bold.nii.gz dim4", "head timing/*.txt", "find . -name report_log.html -print"], tags: ["model", "timing", "log"] },
  { id: "registration-odd", category: "FEAT", title: "Registration looks incorrect", symptom: "Functional, structural, or standard-space boundaries do not align in the report.", resolution: "Inspect the brain-extracted structural image directly, confirm FEAT used the intended structural input, and review the registration method and required files. Do not proceed to group analysis with failed registration.", commands: ["fsleyes example_func2standard.nii.gz $FSLDIR/data/standard/MNI152_T1_2mm.nii.gz &"], tags: ["registration", "structural", "qc"] },
  { id: "fsleyes-no-open", category: "FSLEyes", title: "FSLEyes does not open", symptom: "The command returns without a visible window or the terminal remains occupied.", resolution: "Run from the graphical Neurodesk session and place the process in the background. Confirm that the file exists before launching the viewer.", commands: ["ls -lh image.nii.gz", "fsleyes image.nii.gz &"], tags: ["display", "window", "background"] },
  { id: "overlay-wrong", category: "FSLEyes", title: "Overlays appear incorrect", symptom: "An overlay is offset, invisible, or appears in an unexpected location.", resolution: "Check that images are in compatible spaces, compare dimensions and affine metadata, reset display range, and inspect multiple slices. A color or opacity issue is different from a registration failure.", commands: ["fslinfo background.nii.gz", "fslinfo overlay.nii.gz"], tags: ["overlay", "space", "affine"] },
  { id: "freesurfer-license", category: "fMRIPrep", title: "FreeSurfer license error", symptom: "fMRIPrep stops because it cannot read a valid FreeSurfer license.", resolution: "Place the institutional or personal license file at the documented path, check that it is readable, and pass that exact path to --fs-license-file.", commands: ["ls -l ~/.license", "test -r ~/.license && echo readable"], tags: ["license", "freesurfer"] },
  { id: "fmriprep-memory", category: "fMRIPrep", title: "fMRIPrep runs out of memory", symptom: "The workflow is killed or reports a memory/resource error during registration or surface processing.", resolution: "Use the resource guidance for your environment, reduce parallel workers if appropriate, and resume from a persistent work directory. Do not request more memory than the platform provides.", commands: ["free -h", "df -h"], tags: ["memory", "resources", "workdir"] },
];

export function searchTroubleshooting(query: string): TroubleshootingArticle[] {
  const normalized = query.trim().toLowerCase();
  if (!normalized) return troubleshootingArticles;
  return troubleshootingArticles.filter((article) =>
    [article.title, article.symptom, article.resolution, article.category, ...article.tags]
      .join(" ")
      .toLowerCase()
      .includes(normalized),
  );
}

