const lecture = (deck, slides, note) => ({
  type: "lecture",
  deck,
  slides,
  note,
  visibility: "internal",
});

const repositoryAsset = (asset, note) => ({
  type: "repository-asset",
  asset,
  note,
  visibility: "internal",
});

const scene = ({ id, kind, layout, eyebrow, title, body, bullets, visual, narrationText, sourceRefs = [] }) => ({
  id,
  kind,
  layout,
  display: {
    eyebrow,
    title,
    ...(body ? { body } : {}),
    ...(bullets?.length ? { bullets } : {}),
  },
  ...(visual ? { visual } : {}),
  narrationText,
  sourceRefs,
});

export const editorialV2 = {
  "what-is-fsl": {
    description: "See how FSL's tools divide the work of inspecting, measuring, transforming, modeling, and reporting MRI data.",
    scenes: [
      scene({
        id: "opening",
        kind: "opening",
        layout: "opening",
        eyebrow: "FSL foundations",
        title: "One toolkit, many jobs",
        body: "FSL is a coordinated suite, not one giant application.",
        visual: {
          type: "tool-map",
          items: [
            { label: "FSLEyes", detail: "inspect images", tone: "blue" },
            { label: "FEAT", detail: "model fMRI", tone: "accent" },
            { label: "fslinfo", detail: "read headers", tone: "muted" },
            { label: "fslstats", detail: "summarize values", tone: "coral" },
            { label: "fslmaths", detail: "transform images", tone: "accent" },
          ],
        },
        narrationText: "FSL is a collection of focused neuroimaging tools. Instead of forcing every task into one program, it gives you different tools for viewing images, checking metadata, transforming data, fitting models, and reviewing results. Learning FSL means knowing which tool answers the question in front of you.",
        sourceRefs: [lecture("L01_IntroMRIsafety", [15, 16, 17, 67], "Measurement framing and FSL lab goals")],
      }),
      scene({
        id: "core-idea",
        kind: "explanation",
        layout: "editorial",
        eyebrow: "Choose by purpose",
        title: "The job selects the tool",
        body: "Viewing, modeling, measuring, and transforming are different operations.",
        visual: {
          type: "comparison",
          items: [
            { label: "Inspect", value: "FSLEyes", detail: "See anatomy, overlays, and time series.", tone: "blue" },
            { label: "Model", value: "FEAT", detail: "Estimate task effects and contrasts.", tone: "accent" },
            { label: "Measure", value: "CLI", detail: "Read headers and summarize voxels.", tone: "coral" },
          ],
        },
        narrationText: "Start with the scientific job. FSLEyes is for visual inspection. FEAT configures and evaluates fMRI models. Command-line utilities expose precise metadata, statistics, and image operations. These tools share a workflow, but they do not provide interchangeable evidence.",
        sourceRefs: [lecture("L01_IntroMRIsafety", [15, 16], "fMRI as a measurement workflow")],
      }),
      scene({
        id: "observable-check",
        kind: "evidence",
        layout: "evidence",
        eyebrow: "Real output",
        title: "A report records the chain",
        body: "FEAT links inputs, preprocessing, design, and statistical results.",
        visual: {
          type: "image-evidence",
          asset: "/curriculum/feat-report.png",
          caption: "A completed FEAT report organizes the analysis into reviewable stages.",
        },
        narrationText: "This FEAT report is one example of FSL's division of labor. FEAT organizes the model and its outputs, while visual checks often continue in the report and in FSLEyes. A completed report proves that software ran; it does not by itself prove that the analysis is scientifically valid.",
        sourceRefs: [repositoryAsset("/curriculum/feat-report.png", "Authentic FEAT report evidence")],
      }),
      scene({
        id: "quality-control",
        kind: "quality-control",
        layout: "dashboard",
        eyebrow: "Before interpretation",
        title: "Execution is not validation",
        body: "Each tool produces evidence that still needs a scientific check.",
        visual: {
          type: "checklist",
          items: [
            { label: "Confirm the input", detail: "Is this the intended image, run, and space?" },
            { label: "Inspect the operation", detail: "Does the setting match the analysis plan?" },
            { label: "Read the output", detail: "Does the result support the stated conclusion?" },
          ],
        },
        narrationText: "A command can succeed on the wrong file. A model can finish with a poor design. An overlay can look plausible in one slice and fail elsewhere. Treat every FSL output as evidence to inspect, not as an automatic conclusion.",
        sourceRefs: [lecture("L01_IntroMRIsafety", [29, 30, 31, 32], "Contrast and measurement depend on variability")],
      }),
      scene({
        id: "summary",
        kind: "summary",
        layout: "summary",
        eyebrow: "Takeaway",
        title: "Match tool to question",
        bullets: ["Inspect with FSLEyes", "Model with FEAT", "Measure with focused utilities"],
        narrationText: "FSL is a suite of related tools. Choose the tool by the job, preserve the connection between steps, and inspect what each output actually demonstrates. Successful computation never replaces visual and scientific quality control.",
        sourceRefs: [lecture("L01_IntroMRIsafety", [16, 67], "Measurement limits and FSL workflow goals")],
      }),
    ],
  },

  "how-this-course-works": {
    description: "Use a repeatable study loop that connects explanation, prediction, hands-on work, evidence, and reflection.",
    scenes: [
      scene({
        id: "opening",
        kind: "opening",
        layout: "opening",
        eyebrow: "Your learning loop",
        title: "Understand, then operate",
        body: "The course alternates explanation with observable work in FSL.",
        visual: {
          type: "learning-loop",
          items: [
            { label: "Understand", tone: "accent" },
            { label: "Predict", tone: "blue" },
            { label: "Run", tone: "coral" },
            { label: "Inspect", tone: "accent" },
            { label: "Explain", tone: "blue" },
          ],
        },
        narrationText: "This course is built around a simple loop. First understand what a step is supposed to do. Predict the result, run the step, inspect the evidence, and explain any difference between your prediction and what happened. That loop builds transferable judgment instead of button memory.",
        sourceRefs: [lecture("L01_IntroMRIsafety", [8], "Key-question structure used throughout the lectures")],
      }),
      scene({
        id: "core-idea",
        kind: "explanation",
        layout: "diagram",
        eyebrow: "Predict before clicking",
        title: "Make the result test you",
        body: "A prediction turns software output into feedback about your understanding.",
        visual: {
          type: "learning-loop",
          items: [
            { label: "Question", detail: "What should change?", tone: "blue" },
            { label: "Prediction", detail: "What should appear?", tone: "accent" },
            { label: "Evidence", detail: "What actually happened?", tone: "coral" },
            { label: "Revision", detail: "What explains the gap?", tone: "blue" },
          ],
        },
        narrationText: "Before running a command or changing a FEAT setting, state what you expect. A prediction makes the output diagnostic. If the output differs, the gap may reveal a path error, a misunderstood parameter, or a scientific assumption that needs revision.",
        sourceRefs: [lecture("L09_ExperimentalDesign", [6, 7, 8, 11], "Questions and hypotheses drive design decisions")],
      }),
      scene({
        id: "observable-check",
        kind: "practice",
        layout: "editorial",
        eyebrow: "Set up the session",
        title: "Use two working spaces",
        body: "Keep the lesson visible while you work in Neurodesk or your approved FSL environment.",
        bullets: ["Read one step", "Predict the output", "Record what changed"],
        visual: {
          type: "comparison",
          items: [
            { label: "Lesson", detail: "Purpose, mechanism, and expected evidence", tone: "accent" },
            { label: "Workspace", detail: "Your files, commands, and observed result", tone: "blue" },
          ],
        },
        narrationText: "Keep the explanation beside the working environment. Read one step, make a prediction, and then perform it yourself. Use a notes file to record commands, observations, and unresolved questions. The notes become part of your reproducible reasoning.",
        sourceRefs: [],
      }),
      scene({
        id: "quality-control",
        kind: "quality-control",
        layout: "dashboard",
        eyebrow: "Use examples carefully",
        title: "Expected output is a check",
        body: "Compare after you have predicted and run the step yourself.",
        visual: {
          type: "comparison",
          items: [
            { label: "Copying", value: "Weak", detail: "Matches the example without testing understanding.", tone: "coral" },
            { label: "Comparing", value: "Strong", detail: "Explains why your result agrees or differs.", tone: "accent" },
          ],
        },
        narrationText: "An example is not an answer key to copy. Look at it after you have made a prediction and run the step. Then compare structure, not every character, because file paths and exact values may legitimately differ across environments and datasets.",
        sourceRefs: [],
      }),
      scene({
        id: "summary",
        kind: "summary",
        layout: "summary",
        eyebrow: "Takeaway",
        title: "Practice the reasoning loop",
        bullets: ["Predict before running", "Inspect observable evidence", "Explain every mismatch"],
        narrationText: "Use each lesson as a cycle of understanding, prediction, action, inspection, and explanation. That habit is more valuable than memorizing a menu or command sequence, because it continues to work when the interface or dataset changes.",
        sourceRefs: [lecture("L11_Stats-Advanced", [6], "Models should follow hypotheses about underlying processes")],
      }),
    ],
  },

  "getting-started-with-neurodesk": {
    description: "Choose an approved Neurodesk route, locate persistent storage, and distinguish the base shell from an FSL-enabled terminal.",
    scenes: [
      scene({
        id: "opening",
        kind: "opening",
        layout: "opening",
        eyebrow: "Reproducible environment",
        title: "Start in the right workspace",
        body: "Neurodesk packages neuroimaging tools in a consistent software environment.",
        visual: {
          type: "route-map",
          items: [
            { label: "Access", detail: "Use Play, EDU, or your institution's route." },
            { label: "Storage", detail: "Find the location that persists between sessions." },
            { label: "FSL terminal", detail: "Open the environment with FSL loaded." },
          ],
        },
        narrationText: "Neurodesk provides a consistent environment for neuroimaging software. Your access route may be Neurodesk Play, Neurodesk EDU, or an institutional deployment. The important first steps are to find persistent storage and open a terminal in which FSL is actually available.",
        sourceRefs: [],
      }),
      scene({
        id: "core-idea",
        kind: "explanation",
        layout: "evidence",
        eyebrow: "Find the application",
        title: "Launch FSL deliberately",
        body: "The app workspace separates general tools from software-specific environments.",
        visual: {
          type: "image-evidence",
          asset: "/curriculum/neurodesk-launch.png",
          caption: "The approved course image shows the Neurodesk application workspace and launcher.",
        },
        narrationText: "The application workspace gives you access to packaged tools. Open the FSL tile or the approved FSL terminal rather than assuming the base shell contains every neuroimaging command. The exact arrangement can vary, so identify the tool by its name and purpose rather than by memorizing a screen position.",
        sourceRefs: [repositoryAsset("/curriculum/neurodesk-launch.png", "Approved course image of the application workspace")],
      }),
      scene({
        id: "observable-check",
        kind: "practice",
        layout: "evidence",
        eyebrow: "Verify the environment",
        title: "Ask the shell what it knows",
        body: "A small command can confirm whether FSL is on the active path.",
        visual: {
          type: "code",
          code: "which fslinfo",
          output: "/usr/local/fsl/bin/fslinfo",
        },
        narrationText: "Run which fslinfo in the terminal. A returned path means the shell can locate the program. If the command returns nothing, stop there. You may be in a base terminal, or the FSL environment may not have loaded correctly.",
        sourceRefs: [],
      }),
      scene({
        id: "quality-control",
        kind: "quality-control",
        layout: "dashboard",
        eyebrow: "Protect your work",
        title: "Temporary sessions can disappear",
        body: "Save datasets, scripts, and notes only in the persistent location provided by your environment.",
        visual: {
          type: "comparison",
          items: [
            { label: "Session storage", value: "Temporary", detail: "May vanish when the workspace stops.", tone: "coral" },
            { label: "Persistent storage", value: "Keep", detail: "Use for data, scripts, and written observations.", tone: "accent" },
          ],
        },
        narrationText: "Browser workspaces can contain temporary files that disappear when the session ends. Before downloading data or starting an analysis, identify the persistent storage location provided by your environment. Save your data, scripts, logs, and notes there, then verify that the files remain after reopening the workspace.",
        sourceRefs: [],
      }),
      scene({
        id: "summary",
        kind: "summary",
        layout: "summary",
        eyebrow: "Takeaway",
        title: "Access, storage, environment",
        bullets: ["Use the approved route", "Work in persistent storage", "Verify FSL before analysis"],
        narrationText: "Begin every Neurodesk session by confirming three things: the approved access route, the persistent storage location, and an FSL-enabled terminal. Those checks prevent lost files and confusing command-not-found errors later in the workflow.",
        sourceRefs: [],
      }),
    ],
  },

  "the-terminal": {
    description: "Read a shell command as a precise instruction made from a program, options, and arguments.",
    scenes: [
      scene({
        id: "opening",
        kind: "opening",
        layout: "opening",
        eyebrow: "Linux essentials",
        title: "A command has grammar",
        body: "The shell separates a program, its options, and its arguments.",
        visual: {
          type: "terminal-anatomy",
          items: [
            { label: "program", value: "fslstats", detail: "what runs", tone: "accent" },
            { label: "argument", value: "bold.nii.gz", detail: "what it uses", tone: "blue" },
            { label: "option", value: "-M", detail: "what it reports", tone: "coral" },
          ],
        },
        narrationText: "A terminal command is a precise instruction. The first token usually names the program. Later tokens provide options and arguments. Spaces separate those pieces, capitalization matters, and the shell does not guess which file you intended.",
        sourceRefs: [],
      }),
      scene({
        id: "core-idea",
        kind: "explanation",
        layout: "diagram",
        eyebrow: "Read left to right",
        title: "Program, option, argument",
        body: "Each token changes what the command does or which data it uses.",
        visual: {
          type: "terminal-anatomy",
          items: [
            { label: "program", value: "ls", detail: "list files", tone: "accent" },
            { label: "option", value: "-lh", detail: "details + readable sizes", tone: "coral" },
            { label: "argument", value: "data/", detail: "target directory", tone: "blue" },
          ],
          output: "total 24K\n-rw-r--r--  bold.nii.gz",
        },
        narrationText: "Read the command from left to right. Here, ls is the program, dash l h adds detail and readable sizes, and data slash is the target directory. Changing one token can change the operation, the output, or the file being acted on.",
        sourceRefs: [],
      }),
      scene({
        id: "observable-check",
        kind: "practice",
        layout: "evidence",
        eyebrow: "Read the output",
        title: "Ask before you alter",
        body: "Use non-destructive commands to confirm location and filenames first.",
        visual: {
          type: "code",
          code: "pwd\nls -lh",
          output: "/projects/fsl-course\ntotal 24K\ndrwxr-xr-x  data",
        },
        narrationText: "Before running a command that creates or changes files, ask the shell where you are and what is present. P w d prints the working directory. L s dash l h lists its contents with useful details. Those two observations prevent many avoidable path errors.",
        sourceRefs: [],
      }),
      scene({
        id: "quality-control",
        kind: "quality-control",
        layout: "dashboard",
        eyebrow: "If a command fails",
        title: "Read the error literally",
        body: "The message usually identifies a missing program, option, path, permission, or file.",
        visual: {
          type: "checklist",
          items: [
            { label: "Program found?", detail: "Check the spelling and active environment." },
            { label: "Path correct?", detail: "Print the directory and list the target." },
            { label: "Option supported?", detail: "Consult the command's help text." },
          ],
        },
        narrationText: "Do not respond to an error by changing several things at once. Read the message, identify the failing token, and test one explanation. Confirm the program, the current directory, the target path, and the option. Small checks make the cause observable.",
        sourceRefs: [],
      }),
      scene({
        id: "summary",
        kind: "summary",
        layout: "summary",
        eyebrow: "Takeaway",
        title: "Precision beats guessing",
        bullets: ["Name the program", "Inspect every token", "Verify before changing files"],
        narrationText: "A shell command is structured language. Identify the program, options, and arguments; verify your location and target; and use the output to test your understanding. Precision is the habit that makes command-line work reproducible.",
        sourceRefs: [],
      }),
    ],
  },

  "linux-navigation": {
    description: "Use the working directory, absolute paths, and relative paths to move through a project without losing context.",
    scenes: [
      scene({
        id: "opening",
        kind: "opening",
        layout: "opening",
        eyebrow: "Linux essentials",
        title: "Your location gives paths meaning",
        body: "Relative paths begin from the directory where the shell is currently working.",
        visual: {
          type: "filesystem-tree",
          items: [
            { label: "/projects" },
            { label: "fsl-course" },
            { label: "data" },
            { label: "sub-01", detail: "current directory" },
          ],
        },
        narrationText: "The shell always has a working directory. A relative path is interpreted from that location. An absolute path begins at the filesystem root. Many missing-file errors happen because the file is real, but the command is looking from the wrong context.",
        sourceRefs: [],
      }),
      scene({
        id: "core-idea",
        kind: "explanation",
        layout: "diagram",
        eyebrow: "Two kinds of path",
        title: "Absolute versus relative",
        body: "Both can identify the same file, but they begin from different places.",
        visual: {
          type: "comparison",
          items: [
            { label: "Absolute", value: "/projects/…", detail: "Begins at the filesystem root.", tone: "blue" },
            { label: "Relative", value: "../data/…", detail: "Begins at the working directory.", tone: "accent" },
          ],
        },
        narrationText: "An absolute path states the full route from the root slash. A relative path states the route from where you are now. Relative paths are shorter and portable inside a project, but they only work when the starting context is correct.",
        sourceRefs: [],
      }),
      scene({
        id: "observable-check",
        kind: "practice",
        layout: "evidence",
        eyebrow: "Orient yourself",
        title: "Print, list, then move",
        body: "Use one command to locate yourself, one to inspect, and one to change context.",
        visual: {
          type: "code",
          code: "pwd\nls\ncd data/sub-01",
          output: "/projects/fsl-course\ndata  scripts  notes\n/projects/fsl-course/data/sub-01",
        },
        narrationText: "Use p w d to print your location, l s to inspect what is available, and c d to change directories. After moving, print the location again. This sequence turns an assumed path into observable evidence.",
        sourceRefs: [],
      }),
      scene({
        id: "quality-control",
        kind: "quality-control",
        layout: "dashboard",
        eyebrow: "Missing file?",
        title: "Check context before syntax",
        body: "A correct command can fail when it starts from the wrong directory.",
        visual: {
          type: "checklist",
          items: [
            { label: "Print the directory", detail: "Confirm the starting context." },
            { label: "List the parent", detail: "Verify each folder in the route." },
            { label: "Search narrowly", detail: "Avoid guessing broad paths." },
          ],
        },
        narrationText: "When a file cannot be found, do not repeatedly rewrite the command. Confirm the working directory, list the expected parent folder, and verify each part of the path. If needed, search within the project rather than across the whole system.",
        sourceRefs: [],
      }),
      scene({
        id: "summary",
        kind: "summary",
        layout: "summary",
        eyebrow: "Takeaway",
        title: "Location is part of the command",
        bullets: ["Use pwd for context", "Use ls for evidence", "Use cd deliberately"],
        narrationText: "Navigation is not separate from analysis. Your working directory determines how relative paths are interpreted. Print the context, inspect the route, and move deliberately so every later FSL command acts on the intended data.",
        sourceRefs: [],
      }),
    ],
  },

  "what-is-a-nifti-image": {
    description: "Build a NIfTI image from voxels, slices, volumes, and time while keeping spatial sampling separate from anatomical certainty.",
    scenes: [
      scene({
        id: "opening",
        kind: "opening",
        layout: "opening",
        eyebrow: "Neuroimaging data",
        title: "A NIfTI stores sampled space",
        body: "MRI data are organized as voxels, volumes, and sometimes time.",
        visual: { type: "nifti-stack" },
        narrationText: "A NIfTI file stores numerical samples arranged in space. One sample is a voxel, a tiny three-dimensional box. Voxels form slices, slices form a three-dimensional volume, and repeated volumes form a four-dimensional fMRI time series.",
        sourceRefs: [lecture("L01_IntroMRIsafety", [33, 34, 35], "Voxel and resolution definitions"), lecture("L10_Stats-Basic", [4], "Voxel, volume, run, and analysis hierarchy")],
      }),
      scene({
        id: "core-idea",
        kind: "explanation",
        layout: "diagram",
        eyebrow: "From box to time series",
        title: "Voxel, volume, time",
        body: "The fourth dimension orders repeated 3-D measurements across the run.",
        visual: { type: "nifti-stack" },
        narrationText: "An anatomical image is often one three-dimensional volume. A BOLD image usually contains many volumes sampled at successive time points. The file header records dimensions, voxel sizes, orientation transforms, and timing so software can interpret the array correctly.",
        sourceRefs: [lecture("L10_Stats-Basic", [4], "fMRI data organization")],
      }),
      scene({
        id: "observable-check",
        kind: "practice",
        layout: "evidence",
        eyebrow: "Read the header",
        title: "Dimensions describe the container",
        body: "Inspect size, voxel spacing, and time points before interpreting intensities.",
        visual: {
          type: "code",
          code: "fslinfo bold.nii.gz",
          output: "dim1  64\ndim2  64\ndim3  40\ndim4  240\npixdim4  2.000000",
        },
        narrationText: "Fslinfo exposes the image header. Here, the first three dimensions describe a sixty-four by sixty-four by forty spatial grid. Dimension four contains two hundred forty time points, and pixdim four reports a two-second repetition time. These values describe sampling, not data quality.",
        sourceRefs: [lecture("L01_IntroMRIsafety", [33, 35], "Spatial and temporal sampling")],
      }),
      scene({
        id: "quality-control",
        kind: "quality-control",
        layout: "dashboard",
        eyebrow: "Resolution has limits",
        title: "Smaller voxels are not automatically better",
        body: "Spatial sampling, signal-to-noise, and functional localization are different properties.",
        visual: {
          type: "comparison",
          items: [
            { label: "Voxel size", value: "Sampling", detail: "The dimensions of each measured box.", tone: "blue" },
            { label: "SNR", value: "Stability", detail: "Signal relative to unwanted variation.", tone: "accent" },
            { label: "Functional resolution", value: "Inference", detail: "How precisely activity relates to a process.", tone: "coral" },
          ],
        },
        narrationText: "Voxel dimensions define spatial sampling, not anatomical precision. Smaller voxels can reduce signal-to-noise, and functional localization also depends on physiology, preprocessing, and experimental design. Never translate voxel size directly into certainty about a cognitive process.",
        sourceRefs: [lecture("L01_IntroMRIsafety", [33, 34, 36, 37], "Spatial and functional resolution are distinct")],
      }),
      scene({
        id: "summary",
        kind: "summary",
        layout: "summary",
        eyebrow: "Takeaway",
        title: "Read shape before signal",
        bullets: ["Voxels sample 3-D space", "Volumes can repeat over time", "Headers define interpretation"],
        narrationText: "A NIfTI image is a structured numerical container. Understand its voxels, volumes, dimensions, orientation, and timing before analyzing intensity values. Sampling describes how data were arranged; it does not guarantee what the data can reveal.",
        sourceRefs: [lecture("L01_IntroMRIsafety", [33, 35, 37], "Voxel sampling and inference limits")],
      }),
    ],
  },

  "understanding-bids": {
    description: "Use BIDS folders and filename entities to identify participants, tasks, runs, modalities, events, and metadata without local guesswork.",
    scenes: [
      scene({
        id: "opening",
        kind: "opening",
        layout: "opening",
        eyebrow: "Neuroimaging data",
        title: "Structure is part of the data",
        body: "BIDS makes files understandable to people and software through predictable names.",
        visual: {
          type: "bids-tree",
          items: [
            { label: "subject", value: "sub-01", detail: "participant label" },
            { label: "task", value: "task-memory", detail: "experimental task" },
            { label: "run", value: "run-01", detail: "repeated acquisition" },
          ],
        },
        narrationText: "The Brain Imaging Data Structure, or BIDS, uses predictable folders and filename entities. Those labels tell people and software which participant, session, task, run, and modality a file represents. The structure reduces ambiguity and makes automated workflows safer.",
        sourceRefs: [],
      }),
      scene({
        id: "core-idea",
        kind: "explanation",
        layout: "diagram",
        eyebrow: "Read the filename",
        title: "Entities answer specific questions",
        body: "Each key-value pair identifies one part of the acquisition.",
        visual: {
          type: "bids-tree",
          items: [
            { label: "participant", value: "sub-01", detail: "Whose data?" },
            { label: "task", value: "task-memory", detail: "Which paradigm?" },
            { label: "run", value: "run-01", detail: "Which repetition?" },
            { label: "suffix", value: "bold", detail: "Which data type?" },
          ],
        },
        narrationText: "Read a BIDS filename as a sequence of questions. Sub identifies the participant label. Task identifies the paradigm. Run distinguishes repeated acquisitions. The suffix, such as bold or T one w, identifies the data type. Underscores separate entities; hyphens separate keys from values.",
        sourceRefs: [],
      }),
      scene({
        id: "observable-check",
        kind: "practice",
        layout: "editorial",
        eyebrow: "Follow the relationship",
        title: "Image, events, metadata",
        body: "A functional run is interpreted with its matching events table and JSON sidecar.",
        visual: {
          type: "comparison",
          items: [
            { label: "BOLD", value: ".nii.gz", detail: "Measured four-dimensional image", tone: "blue" },
            { label: "Events", value: ".tsv", detail: "Onsets, durations, and trial information", tone: "accent" },
            { label: "Metadata", value: ".json", detail: "Acquisition details and timing", tone: "coral" },
          ],
        },
        narrationText: "A functional NIfTI does not stand alone. Its matching events table describes what happened during the run, and the JSON sidecar records acquisition metadata. Shared entities in the filenames let you connect those files without relying on memory.",
        sourceRefs: [],
      }),
      scene({
        id: "quality-control",
        kind: "quality-control",
        layout: "dashboard",
        eyebrow: "Responsible naming",
        title: "Identifiers do not belong in filenames",
        body: "Use study labels rather than names, medical-record numbers, or other direct identifiers.",
        visual: {
          type: "comparison",
          items: [
            { label: "Direct identity", value: "Remove", detail: "Names and record numbers expose participants.", tone: "coral" },
            { label: "Study label", value: "Use", detail: "A coded participant label supports de-identification.", tone: "accent" },
          ],
        },
        narrationText: "BIDS structure supports responsible sharing only when participant labels are de-identified. Do not place names, medical-record numbers, or other direct identifiers in filenames. Brain images may also require defacing and institutional review before they are shared.",
        sourceRefs: [lecture("L12_EthicalIssues", [12, 13], "Private health information and MRI anonymization")],
      }),
      scene({
        id: "summary",
        kind: "summary",
        layout: "summary",
        eyebrow: "Takeaway",
        title: "Let the name explain the file",
        bullets: ["Read entities left to right", "Match images with sidecars", "Keep identifiers out"],
        narrationText: "BIDS makes file identity explicit. Decode the entities, follow shared labels across images, events, and metadata, and protect participant identity. Good structure is not cosmetic; it is part of reproducible and responsible analysis.",
        sourceRefs: [lecture("L12_EthicalIssues", [12, 13], "Responsible data sharing")],
      }),
    ],
  },

  "introduction-to-fsleyes": {
    description: "Use FSLEyes to inspect image orientation, coverage, intensity, and overlay order across three anatomical planes.",
    scenes: [
      scene({
        id: "opening",
        kind: "opening",
        layout: "opening",
        eyebrow: "Visual inspection",
        title: "Looking is part of analysis",
        body: "FSLEyes makes geometry, coverage, intensity, and alignment directly observable.",
        visual: {
          type: "comparison",
          items: [
            { label: "Sagittal", detail: "side view", tone: "blue" },
            { label: "Coronal", detail: "front view", tone: "accent" },
            { label: "Axial", detail: "top view", tone: "coral" },
          ],
        },
        narrationText: "Visual inspection is an analysis step, not decoration. FSLEyes shows the same coordinate in sagittal, coronal, and axial planes. It lets you inspect orientation, brain coverage, image intensity, and the relationship between overlays before trusting a pipeline result.",
        sourceRefs: [lecture("L01_IntroMRIsafety", [29, 31, 33, 34], "Contrast and voxel sampling")],
      }),
      scene({
        id: "core-idea",
        kind: "explanation",
        layout: "evidence",
        eyebrow: "One location, three views",
        title: "Crosshairs connect the planes",
        body: "Moving one view updates the same anatomical coordinate in the other two.",
        visual: {
          type: "image-evidence",
          asset: "/curriculum/fsleyes-timeseries.png",
          caption: "The approved FSLEyes image shows orthographic views, overlays, and a time-series panel.",
        },
        narrationText: "The orthographic display shows three views of one location. Crosshairs connect those planes, so a movement in one view updates the others. The overlay list controls which images are visible, their order, opacity, and color mapping.",
        sourceRefs: [repositoryAsset("/curriculum/fsleyes-timeseries.png", "Approved FSLEyes evidence")],
      }),
      scene({
        id: "observable-check",
        kind: "evidence",
        layout: "evidence",
        eyebrow: "Inspect the acquisition",
        title: "Check orientation and coverage",
        body: "Look through the whole brain before preprocessing or modeling.",
        visual: {
          type: "image-evidence",
          asset: "/curriculum/fsleyes-timeseries.png",
          caption: "Inspect multiple slices rather than accepting the central view alone.",
        },
        narrationText: "Scroll from one end of the brain to the other. Confirm that left and right orientation are understood, the expected anatomy is covered, and no large region is missing or severely distorted. A later analysis cannot recover anatomy that was never acquired.",
        sourceRefs: [lecture("L08_SignalNoisePreprocessing", [42, 45, 46, 47], "Visual quality assurance and motion artifacts"), repositoryAsset("/curriculum/fsleyes-timeseries.png", "Approved FSLEyes evidence")],
      }),
      scene({
        id: "quality-control",
        kind: "quality-control",
        layout: "dashboard",
        eyebrow: "Do not trust one slice",
        title: "Plausible is not aligned",
        body: "Central overlap can hide failures near frontal, posterior, superior, or inferior boundaries.",
        visual: {
          type: "checklist",
          items: [
            { label: "Inspect boundaries", detail: "Follow cortex, ventricles, and major landmarks." },
            { label: "Inspect many slices", detail: "Check the whole volume, not one center image." },
            { label: "Adjust display", detail: "Opacity and contrast should reveal disagreement." },
          ],
        },
        narrationText: "Two images can overlap near the center and still be misregistered elsewhere. Inspect multiple slices and anatomical boundaries. Adjust opacity and color mapping so disagreement is visible. A reassuring first impression is not a quality-control result.",
        sourceRefs: [lecture("L08_SignalNoisePreprocessing", [54, 55, 58, 59, 60], "Registration, normalization, and coordinates")],
      }),
      scene({
        id: "summary",
        kind: "summary",
        layout: "summary",
        eyebrow: "Takeaway",
        title: "Inspect before you infer",
        bullets: ["Orient in three planes", "Check full brain coverage", "Make misalignment visible"],
        narrationText: "Use FSLEyes to understand the image before relying on derived results. Orient yourself in three planes, inspect coverage across the volume, and compare overlays at visible boundaries. Visual evidence is a required part of quality control.",
        sourceRefs: [lecture("L08_SignalNoisePreprocessing", [42, 54, 58], "Quality assurance and registration")],
      }),
    ],
  },

  "overlays-atlases-and-time-series": {
    description: "Combine aligned overlays, voxel time series, and probabilistic atlas labels without treating any one view as ground truth.",
    scenes: [
      scene({
        id: "opening",
        kind: "opening",
        layout: "opening",
        eyebrow: "Multiple evidence sources",
        title: "One coordinate, several questions",
        body: "Overlays show space, time series show change, and atlases provide probabilistic labels.",
        visual: {
          type: "comparison",
          items: [
            { label: "Overlay", value: "Where?", detail: "Compare images in the same space.", tone: "blue" },
            { label: "Time series", value: "When?", detail: "Inspect change across volumes.", tone: "accent" },
            { label: "Atlas", value: "What label?", detail: "Reference probabilistic anatomy.", tone: "coral" },
          ],
        },
        narrationText: "A single coordinate can support several observations. Overlays compare spatial relationships. A time-series plot shows how signal changes across volumes. An atlas lookup supplies a reference label. These sources complement one another, but none should be treated as unquestionable ground truth.",
        sourceRefs: [lecture("L08_SignalNoisePreprocessing", [54, 56, 58, 60], "Registration and standardized spaces"), lecture("L10_Stats-Basic", [38, 39, 42, 43, 44], "ROI and visualization choices")],
      }),
      scene({
        id: "core-idea",
        kind: "explanation",
        layout: "evidence",
        eyebrow: "Compare aligned images",
        title: "Overlay order changes what you see",
        body: "Opacity, color map, and display range can reveal or conceal disagreement.",
        visual: {
          type: "image-evidence",
          asset: "/curriculum/fsleyes-timeseries.png",
          caption: "FSLEyes combines orthographic overlays with a signal plot at the selected location.",
        },
        narrationText: "The upper overlay can hide the image beneath it. Use opacity, color maps, and display ranges to expose boundaries in both images. A good display does not make alignment true; it makes agreement and disagreement easier to inspect.",
        sourceRefs: [repositoryAsset("/curriculum/fsleyes-timeseries.png", "Approved overlay and time-series evidence")],
      }),
      scene({
        id: "observable-check",
        kind: "evidence",
        layout: "evidence",
        eyebrow: "Read signal over time",
        title: "A voxel is a time series",
        body: "In 4-D data, the selected spatial sample has one value for every volume.",
        visual: {
          type: "image-evidence",
          asset: "/curriculum/fsleyes-timeseries.png",
          caption: "The time-series panel plots the selected location across the run.",
        },
        narrationText: "In a four-dimensional BOLD image, each voxel contains a sequence of values. The plot shows that sequence across the run. Spikes, slow drift, and task-related structure are different patterns; seeing a change does not yet identify its cause.",
        sourceRefs: [lecture("L08_SignalNoisePreprocessing", [5, 15, 19, 20], "Signal size and sources of variability"), repositoryAsset("/curriculum/fsleyes-timeseries.png", "Approved time-series evidence")],
      }),
      scene({
        id: "quality-control",
        kind: "quality-control",
        layout: "dashboard",
        eyebrow: "Use atlases cautiously",
        title: "A label is a reference",
        body: "Atlas boundaries summarize populations and may not match one participant exactly.",
        visual: {
          type: "comparison",
          items: [
            { label: "Coordinate", detail: "The selected location in the displayed space.", tone: "blue" },
            { label: "Probability", detail: "How consistently an atlas assigns a label.", tone: "accent" },
            { label: "Participant", detail: "Individual anatomy can differ from the atlas.", tone: "coral" },
          ],
        },
        narrationText: "An atlas label is a reference derived from a template or population. It may be probabilistic, and individual anatomy varies. Confirm the coordinate space, inspect the participant's anatomy, and report uncertainty rather than presenting an atlas boundary as exact truth.",
        sourceRefs: [lecture("L08_SignalNoisePreprocessing", [55, 56, 57, 58, 61], "Anatomical variability and standardized spaces")],
      }),
      scene({
        id: "summary",
        kind: "summary",
        layout: "summary",
        eyebrow: "Takeaway",
        title: "Combine evidence, preserve uncertainty",
        bullets: ["Compare spatial boundaries", "Inspect change over time", "Treat atlas labels as probabilistic"],
        narrationText: "Use overlays, time series, and atlas labels together. Confirm spatial alignment, inspect temporal behavior, and keep atlas uncertainty visible. A defensible interpretation states what each view contributes and what it cannot establish.",
        sourceRefs: [lecture("L10_Stats-Basic", [42, 43, 44, 46], "Visualization choices and interpretation limits")],
      }),
    ],
  },

  "fslinfo-and-fslstats": {
    description: "Separate image metadata from value summaries and make the contributing voxel set explicit before interpreting a number.",
    scenes: [
      scene({
        id: "opening",
        kind: "opening",
        layout: "opening",
        eyebrow: "Command-line measurement",
        title: "Container facts versus voxel values",
        body: "Fslinfo describes the image; fslstats summarizes selected intensities.",
        visual: {
          type: "metadata-stats",
          items: [
            { label: "dim4", value: "240" },
            { label: "pixdim1", value: "3 mm" },
            { label: "pixdim4", value: "2 s" },
            { label: "mean", value: "812.4" },
            { label: "volume", value: "184,320 mm³" },
            { label: "range", value: "0 … 4,926" },
          ],
        },
        narrationText: "Fslinfo and fslstats answer different questions. Fslinfo reads the NIfTI header and describes the image container. Fslstats calculates summaries from voxel values. A statistic is meaningful only when you know which image and which voxels contributed to it.",
        sourceRefs: [lecture("L08_SignalNoisePreprocessing", [5, 6], "fMRI signal is small relative to variability"), lecture("L10_Stats-Basic", [5, 6, 7], "Purpose and interpretation of statistical summaries")],
      }),
      scene({
        id: "core-idea",
        kind: "explanation",
        layout: "diagram",
        eyebrow: "Ask the right question",
        title: "Metadata and statistics differ",
        body: "Dimensions describe arrangement; statistics describe values inside a selected voxel set.",
        visual: {
          type: "comparison",
          items: [
            { label: "fslinfo", value: "Structure", detail: "Dimensions, spacing, orientation, and timing.", tone: "blue" },
            { label: "fslstats", value: "Values", detail: "Mean, range, percentiles, and voxel volume.", tone: "accent" },
          ],
        },
        narrationText: "Use fslinfo when the question is about structure: dimensions, voxel spacing, orientation, or timing. Use fslstats when the question is about intensity values. The two outputs complement one another, but one cannot substitute for the other.",
        sourceRefs: [lecture("L01_IntroMRIsafety", [29, 31, 33, 35], "Contrast, voxel size, and temporal sampling")],
      }),
      scene({
        id: "observable-check",
        kind: "practice",
        layout: "evidence",
        eyebrow: "Read a targeted result",
        title: "State what was measured",
        body: "Pair every reported value with the image, mask, threshold, and option that produced it.",
        visual: {
          type: "code",
          code: "fslstats brain_mask.nii.gz -V",
          output: "68234  184231.8",
        },
        narrationText: "With dash V, fslstats reports the number of nonzero voxels followed by their physical volume in cubic millimetres. Those values describe the selected image. They do not automatically describe the whole brain, because zeros, thresholds, and masks determine which voxels are counted.",
        sourceRefs: [lecture("L10_Stats-Basic", [38, 39], "Changing the basis of a statistical summary with an ROI")],
      }),
      scene({
        id: "quality-control",
        kind: "quality-control",
        layout: "dashboard",
        eyebrow: "Before reporting a number",
        title: "Make the voxel set visible",
        body: "A precise statistic can still summarize the wrong anatomy.",
        visual: {
          type: "checklist",
          items: [
            { label: "Confirm the image", detail: "Check filename, dimensions, and space." },
            { label: "Inspect the mask", detail: "Overlay it on the exact source image." },
            { label: "Name the operation", detail: "Record thresholds and options with the value." },
          ],
        },
        narrationText: "A numerical result can be perfectly computed and scientifically wrong. Confirm the input image and coordinate space. If a mask is involved, overlay it on the exact source data. Record the option and threshold so another person can reproduce the voxel set.",
        sourceRefs: [lecture("L10_Stats-Basic", [38, 39, 40], "ROI selection and multiple-comparison implications")],
      }),
      scene({
        id: "summary",
        kind: "summary",
        layout: "summary",
        eyebrow: "Takeaway",
        title: "Describe both data and selection",
        bullets: ["Use fslinfo for structure", "Use fslstats for values", "Show which voxels contributed"],
        narrationText: "Use fslinfo to understand the image container and fslstats to summarize values. Never report a number without the image, option, threshold, and voxel selection that define it. Context turns output into interpretable evidence.",
        sourceRefs: [lecture("L10_Stats-Basic", [5, 6, 7], "Statistics assess data quality and hypotheses")],
      }),
    ],
  },

  "fslmaths-and-fslmeants": {
    description: "Transform an image, inspect the resulting mask, and then extract a mean time series from spatially compatible data.",
    scenes: [
      scene({
        id: "opening",
        kind: "opening",
        layout: "opening",
        eyebrow: "Image operations",
        title: "Transform first, measure second",
        body: "Fslmaths creates an image; fslmeants extracts a time series from selected voxels.",
        visual: { type: "mask-measure" },
        narrationText: "Fslmaths and fslmeants often appear together, but they do different jobs. Fslmaths applies operations in sequence and writes a new image. Fslmeants uses a mask to summarize a four-dimensional time series across selected voxels.",
        sourceRefs: [lecture("L10_Stats-Basic", [38, 39], "ROI-based measurement changes the basis of a summary")],
      }),
      scene({
        id: "core-idea",
        kind: "explanation",
        layout: "diagram",
        eyebrow: "Build a derived image",
        title: "Operations run left to right",
        body: "Each fslmaths option acts on the result of the previous option.",
        visual: {
          type: "learning-loop",
          items: [
            { label: "Input", detail: "stat image", tone: "blue" },
            { label: "Threshold", detail: "keep ≥ 2.3", tone: "coral" },
            { label: "Binarize", detail: "0 or 1", tone: "accent" },
            { label: "Output", detail: "mask image", tone: "blue" },
          ],
        },
        narrationText: "Fslmaths reads an input, applies operations from left to right, and writes an output. A threshold removes values below a cutoff. Binarization converts the remaining selection to ones. The output is a new mask, not a label permanently attached to the original image.",
        sourceRefs: [],
      }),
      scene({
        id: "observable-check",
        kind: "practice",
        layout: "evidence",
        eyebrow: "Create, inspect, extract",
        title: "Make the spatial choice explicit",
        body: "The mask defines which voxel time series enter the mean.",
        visual: {
          type: "code",
          code: "fslmaths zstat1 -thr 2.3 -bin roi_mask\nfslmeants -i filtered_func_data -m roi_mask -o roi.txt",
          output: "roi.txt: one mean value per volume",
        },
        narrationText: "This example thresholds a statistical image, binarizes the result, and saves a mask. Fslmeants then extracts the mean BOLD value inside that mask for every volume. The output is a time series whose meaning depends entirely on the mask and source image.",
        sourceRefs: [lecture("L10_Stats-Basic", [38, 39], "ROI definition and interpretation")],
      }),
      scene({
        id: "quality-control",
        kind: "quality-control",
        layout: "dashboard",
        eyebrow: "Before extraction",
        title: "Matching dimensions are not enough",
        body: "The mask and BOLD image must also represent the same spatial location.",
        visual: {
          type: "checklist",
          items: [
            { label: "Check dimensions", detail: "Grid sizes and voxel spacing must be compatible." },
            { label: "Check transforms", detail: "Headers should describe the intended space." },
            { label: "Check the overlay", detail: "The mask must cover the intended anatomy." },
          ],
        },
        narrationText: "Two files can share dimensions while representing different anatomy. Check the headers, then overlay the mask on the exact image used for extraction. Confirm coverage across slices. A time series extracted from the wrong space is precise but meaningless.",
        sourceRefs: [lecture("L08_SignalNoisePreprocessing", [54, 58, 60, 61], "Registration and standardized-space considerations")],
      }),
      scene({
        id: "summary",
        kind: "summary",
        layout: "summary",
        eyebrow: "Takeaway",
        title: "Transform, verify, then measure",
        bullets: ["Write a new image", "Inspect spatial alignment", "Extract from the verified mask"],
        narrationText: "Use fslmaths to create a derived image and fslmeants to measure a time series within a mask. Preserve the operation order, inspect the mask in the source space, and only then interpret the extracted values.",
        sourceRefs: [lecture("L08_SignalNoisePreprocessing", [62, 63, 64, 65, 66], "Spatial operations can alter localization")],
      }),
    ],
  },

  "what-first-level-means": {
    description: "Model one participant's single run at every voxel and keep that scope distinct from within-subject and population inference.",
    scenes: [
      scene({
        id: "opening",
        kind: "opening",
        layout: "opening",
        eyebrow: "First-level fMRI",
        title: "One participant, one run",
        body: "First-level analysis links one BOLD time series to one design at every voxel.",
        visual: {
          type: "analysis-levels",
          items: [
            { label: "First level", detail: "one run" },
            { label: "Within subject", detail: "combine runs" },
            { label: "Group level", detail: "combine participants" },
          ],
        },
        narrationText: "A first-level analysis models one run from one participant. At every voxel, it compares the observed BOLD time series with predicted task and nuisance patterns. The resulting estimates belong to that run; they are not yet evidence about a population.",
        sourceRefs: [lecture("L10_Stats-Basic", [4], "Analysis hierarchy from voxel to group"), lecture("L09_ExperimentalDesign", [2, 3], "GLM relationship between voxel data and hypotheses")],
      }),
      scene({
        id: "core-idea",
        kind: "explanation",
        layout: "diagram",
        eyebrow: "The same model repeats",
        title: "Fit the design at every voxel",
        body: "The design stays fixed while the measured time series changes across space.",
        visual: { type: "glm" },
        narrationText: "The design matrix describes expected patterns across the run. FEAT fits that same set of predictors separately to each voxel's measured time series. Beta estimates describe the fitted contribution of each column, and residuals contain structure the model did not explain.",
        sourceRefs: [lecture("L10_Stats-Basic", [14, 15, 16], "Basic GLM and voxelwise model")],
      }),
      scene({
        id: "observable-check",
        kind: "evidence",
        layout: "evidence",
        eyebrow: "Inspect the model",
        title: "Columns must match the run",
        body: "Timing, confounds, and contrast weights should describe this exact acquisition.",
        visual: {
          type: "image-evidence",
          asset: "/curriculum/feat-design-matrix.png",
          caption: "The FEAT design matrix makes predictor timing and relative structure visible.",
        },
        narrationText: "Before interpreting a first-level result, inspect the design matrix. Confirm that task columns match the run's timing, nuisance columns have the expected length, and contrasts point to the intended explanatory variables. A design from another run can fit without answering the correct question.",
        sourceRefs: [repositoryAsset("/curriculum/feat-design-matrix.png", "Authentic FEAT design evidence"), lecture("L10_Stats-Basic", [17, 18, 19, 20], "Contrasts, nuisance regressors, and column dependence")],
      }),
      scene({
        id: "quality-control",
        kind: "quality-control",
        layout: "dashboard",
        eyebrow: "Scope of inference",
        title: "A run is not a population",
        body: "Higher-level models are required to combine runs and generalize across participants.",
        visual: {
          type: "comparison",
          items: [
            { label: "First level", value: "Run", detail: "Estimates effects within one acquisition.", tone: "blue" },
            { label: "Fixed effects", value: "Subject", detail: "Combines runs without population variance.", tone: "accent" },
            { label: "Random effects", value: "Population", detail: "Models variation across participants.", tone: "coral" },
          ],
        },
        narrationText: "First-level results describe one run. Fixed-effects combinations can summarize multiple runs from a participant, but they still do not model population variability. Random-effects analysis uses variation across participants to support population-level inference.",
        sourceRefs: [lecture("L10_Stats-Basic", [22, 23, 24], "Fixed-effects and random-effects scope")],
      }),
      scene({
        id: "summary",
        kind: "summary",
        layout: "summary",
        eyebrow: "Takeaway",
        title: "Keep the level explicit",
        bullets: ["One run defines first level", "Fit the GLM voxel by voxel", "Generalization needs higher levels"],
        narrationText: "First-level analysis fits one run from one participant at every voxel. Inspect the design and contrasts in that scope, then use appropriate higher-level models for within-subject combinations and population inference. Never let the image hide the level of analysis.",
        sourceRefs: [lecture("L10_Stats-Basic", [4, 22, 23, 24], "Analysis hierarchy and inference scope")],
      }),
    ],
  },

  "what-is-a-glm": {
    description: "Build the fMRI general linear model from observed BOLD signal, predictor columns, fitted estimates, and residual error.",
    scenes: [
      scene({
        id: "opening",
        kind: "opening",
        layout: "opening",
        eyebrow: "Modeling BOLD",
        title: "Explain signal with a design",
        body: "The GLM represents measured BOLD as modeled predictors plus residuals.",
        visual: { type: "glm" },
        narrationText: "The general linear model represents a measured BOLD time series as a weighted combination of predictors plus residual error. In compact form, Y equals X beta plus epsilon. FEAT fits this relationship separately at every voxel.",
        sourceRefs: [lecture("L08_SignalNoisePreprocessing", [3], "Signal, model, amplitude, and noise"), lecture("L09_ExperimentalDesign", [2, 3], "Voxelwise GLM overview"), lecture("L10_Stats-Basic", [14, 15], "Basic GLM form")],
      }),
      scene({
        id: "core-idea",
        kind: "explanation",
        layout: "diagram",
        eyebrow: "Read the equation",
        title: "Four parts, four meanings",
        body: "Observed data, design, estimates, and residuals must remain conceptually separate.",
        visual: { type: "glm" },
        narrationText: "Y is the observed BOLD time series. X is the design matrix containing task and nuisance predictors. Beta contains the fitted contribution of each column. Epsilon contains the remaining structure. Residuals are unexplained by the model; they are not automatically random or harmless.",
        sourceRefs: [lecture("L10_Stats-Basic", [14, 15, 16, 18], "GLM matrices and regressors")],
      }),
      scene({
        id: "observable-check",
        kind: "evidence",
        layout: "evidence",
        eyebrow: "Inspect X before β",
        title: "The design encodes the hypothesis",
        body: "Column order, timing, scaling, and dependence determine how estimates are interpreted.",
        visual: {
          type: "image-evidence",
          asset: "/curriculum/feat-design-matrix.png",
          caption: "The FEAT design matrix is the visible representation of X.",
        },
        narrationText: "The design matrix is not a decorative preview. Its columns encode the model. Confirm the timing, identify task and nuisance regressors, and look for strong dependence between columns. Beta estimates are conditional on all the other predictors in X.",
        sourceRefs: [repositoryAsset("/curriculum/feat-design-matrix.png", "Authentic FEAT design matrix"), lecture("L10_Stats-Basic", [16, 18, 19, 20], "Regressors and orthogonalization")],
      }),
      scene({
        id: "quality-control",
        kind: "quality-control",
        layout: "dashboard",
        eyebrow: "Model limits",
        title: "A fit can answer the wrong question",
        body: "Good computation cannot rescue a design that misrepresents the hypothesis or noise structure.",
        visual: {
          type: "checklist",
          items: [
            { label: "Hypothesis first", detail: "Columns should represent the proposed processes." },
            { label: "Confounds visible", detail: "Model structured nuisance variation explicitly." },
            { label: "Residuals inspected", detail: "Look for drift, spikes, or other remaining structure." },
          ],
        },
        narrationText: "A GLM can fit successfully and still answer the wrong scientific question. The model should follow the hypothesis about underlying processes, not merely every stimulus label. Nuisance structure must be addressed, and residual patterns should be inspected rather than dismissed as noise.",
        sourceRefs: [lecture("L11_Stats-Advanced", [4, 6, 21], "Regressors versus contrasts and hypothesis-driven modeling"), lecture("L08_SignalNoisePreprocessing", [15, 19, 37], "Structured and temporally correlated noise")],
      }),
      scene({
        id: "summary",
        kind: "summary",
        layout: "summary",
        eyebrow: "Takeaway",
        title: "The model makes assumptions visible",
        bullets: ["Y is observed BOLD", "X and β encode the fit", "ε remains unexplained"],
        narrationText: "The fMRI GLM separates measured data, modeled predictors, fitted estimates, and residuals. Read those parts distinctly, inspect the design before the results, and remember that a successful fit only supports claims represented by the model.",
        sourceRefs: [lecture("L10_Stats-Basic", [14, 15, 16, 17], "GLM form and contrast setup")],
      }),
    ],
  },

  "experimental-timing-files": {
    description: "Translate experimental events into FSL onset-duration-amplitude rows while preserving the design's detection and estimation goals.",
    scenes: [
      scene({
        id: "opening",
        kind: "opening",
        layout: "opening",
        eyebrow: "Experimental timing",
        title: "Events become model input",
        body: "FSL timing files encode when a condition starts, how long it lasts, and its amplitude.",
        visual: {
          type: "timing-strip",
          items: [
            { label: "0 s", detail: "12-second block", tone: "blue" },
            { label: "24 s", detail: "brief event", value: "event", tone: "accent" },
            { label: "39 s", detail: "brief event", value: "event", tone: "coral" },
            { label: "60 s", detail: "12-second block", tone: "blue" },
          ],
        },
        narrationText: "Experimental timing files translate the task into model input. Each row states an onset in seconds, a duration in seconds, and an amplitude. Each condition usually receives its own file so the design can form a separate explanatory variable.",
        sourceRefs: [lecture("L09_ExperimentalDesign", [13, 16, 18, 28], "Block and event-related design structure")],
      }),
      scene({
        id: "core-idea",
        kind: "explanation",
        layout: "diagram",
        eyebrow: "Three columns",
        title: "Onset, duration, amplitude",
        body: "Every row describes one modeled event or block in scanner time.",
        visual: {
          type: "comparison",
          items: [
            { label: "Onset", value: "seconds", detail: "When the event begins.", tone: "blue" },
            { label: "Duration", value: "seconds", detail: "How long the modeled input lasts.", tone: "accent" },
            { label: "Amplitude", value: "weight", detail: "Its modeled height or parametric value.", tone: "coral" },
          ],
        },
        narrationText: "The first column is onset measured from the start of the run. The second is duration. The third is amplitude, often one for a simple condition but variable for parametric designs. These values describe the neural-event model before convolution with the hemodynamic response.",
        sourceRefs: [lecture("L09_ExperimentalDesign", [28, 31, 34, 35], "Event timing, spacing, and jitter")],
      }),
      scene({
        id: "observable-check",
        kind: "practice",
        layout: "evidence",
        eyebrow: "Validate the rows",
        title: "Timing must fit the run",
        body: "Onsets, durations, and amplitudes should agree with the event table and scan length.",
        visual: {
          type: "code",
          code: "0    12    1\n24    1    1\n39    1    1\n60   12    1",
          output: "onset   duration   amplitude",
        },
        narrationText: "Read each row against the event table. Confirm the units are seconds, not volumes. Check that onsets are nonnegative, durations are plausible, and no event extends beyond the run. Then plot or preview the resulting model rather than trusting the text file alone.",
        sourceRefs: [lecture("L09_ExperimentalDesign", [16, 17, 24, 32, 35], "Timing influences the hemodynamic model and efficiency")],
      }),
      scene({
        id: "quality-control",
        kind: "quality-control",
        layout: "dashboard",
        eyebrow: "Design tradeoffs",
        title: "Timing changes what you can estimate",
        body: "Blocked and jittered event-related designs emphasize different scientific goals.",
        visual: {
          type: "comparison",
          items: [
            { label: "Blocked", value: "Detect", detail: "Strong sustained differences, limited event separation.", tone: "blue" },
            { label: "Jittered events", value: "Estimate", detail: "Separates trials and response shapes more flexibly.", tone: "accent" },
            { label: "Mixed", value: "Combine", detail: "Models sustained and transient effects together.", tone: "coral" },
          ],
        },
        narrationText: "Timing is part of experimental design, not file formatting. Blocked designs often provide strong detection power. Jittered event-related designs improve separation and estimation of individual events. Mixed designs can model sustained and transient effects. The best choice depends on the hypothesis and constraints.",
        sourceRefs: [lecture("L09_ExperimentalDesign", [8, 13, 23, 24, 26, 29, 37, 41, 42, 44], "Detection-estimation tradeoffs and design efficiency")],
      }),
      scene({
        id: "summary",
        kind: "summary",
        layout: "summary",
        eyebrow: "Takeaway",
        title: "Timing encodes the experiment",
        bullets: ["Use seconds from run start", "Validate every event", "Match timing to the hypothesis"],
        narrationText: "A three-column file is a compact model of the experiment. Encode onset, duration, and amplitude accurately; validate the rows against the run; and remember that timing determines which effects the design can detect and estimate.",
        sourceRefs: [lecture("L09_ExperimentalDesign", [37, 44, 45, 46], "Efficient design and summary principles")],
      }),
    ],
  },

  "what-is-an-ev": {
    description: "Treat an explanatory variable as one hypothesized pattern in the design matrix and distinguish task, parametric, and nuisance meanings.",
    scenes: [
      scene({
        id: "opening",
        kind: "opening",
        layout: "opening",
        eyebrow: "Design matrix",
        title: "One column, one modeled pattern",
        body: "An explanatory variable represents variation expected to explain part of the BOLD signal.",
        visual: {
          type: "ev-columns",
          items: [
            { label: "Task EV", detail: "condition timing", tone: "accent" },
            { label: "Parametric EV", detail: "trial-by-trial value", tone: "blue" },
            { label: "Nuisance EV", detail: "motion or drift", tone: "coral" },
          ],
        },
        narrationText: "An explanatory variable, or EV, is one modeled pattern in the design matrix. A task EV represents an experimental condition. A parametric EV represents graded trial values. A nuisance EV represents structured variation that is not the effect of interest.",
        sourceRefs: [lecture("L10_Stats-Basic", [15, 16, 18, 19], "Design matrix, regressors, and categorical versus parametric predictors")],
      }),
      scene({
        id: "core-idea",
        kind: "explanation",
        layout: "diagram",
        eyebrow: "Meaning comes from the hypothesis",
        title: "Columns are not interchangeable",
        body: "Two EVs can look similar but support different interpretations.",
        visual: {
          type: "ev-columns",
          items: [
            { label: "Condition", detail: "Was the task present?", tone: "accent" },
            { label: "Difficulty", detail: "Did response scale with level?", tone: "blue" },
            { label: "Motion", detail: "Did movement explain variation?", tone: "coral" },
          ],
        },
        narrationText: "The interpretation of an EV comes from how it was constructed and why it belongs in the model. A condition column asks about an average task effect. A parametric column asks whether response changes with a value. A motion column controls nuisance variation rather than testing the task.",
        sourceRefs: [lecture("L11_Stats-Advanced", [4, 6], "Regressors and hypotheses about cognitive processes")],
      }),
      scene({
        id: "observable-check",
        kind: "evidence",
        layout: "evidence",
        eyebrow: "Inspect the columns",
        title: "Verify order, timing, and dependence",
        body: "Every contrast and beta estimate depends on the final design matrix.",
        visual: {
          type: "image-evidence",
          asset: "/curriculum/feat-design-matrix.png",
          caption: "FEAT displays the final EV columns and their temporal relationships.",
        },
        narrationText: "Inspect the design matrix after EV construction. Confirm that each column has the expected timing and order. Look for near-duplicate patterns or strong correlation. When predictors overlap, each beta estimate describes a contribution after accounting for the other columns.",
        sourceRefs: [repositoryAsset("/curriculum/feat-design-matrix.png", "Authentic FEAT EV evidence"), lecture("L10_Stats-Basic", [16, 18, 20], "Regressors and column dependence")],
      }),
      scene({
        id: "quality-control",
        kind: "quality-control",
        layout: "dashboard",
        eyebrow: "Model the process",
        title: "Do not copy the stimulus list",
        body: "The design should represent hypothesized causes of variation, not every available label.",
        visual: {
          type: "checklist",
          items: [
            { label: "Name the process", detail: "What variation should this EV capture?" },
            { label: "Define the timing", detail: "How does the process unfold across the run?" },
            { label: "State the contrast", detail: "Which EV combination answers the hypothesis?" },
          ],
        },
        narrationText: "A complex stimulus does not automatically require a column for every feature. Build the model around the hypothesized processes and comparisons. An EV is justified by the scientific question and design, not merely by the availability of a label.",
        sourceRefs: [lecture("L11_Stats-Advanced", [6, 7, 8], "Complex models should be justified by underlying processes")],
      }),
      scene({
        id: "summary",
        kind: "summary",
        layout: "summary",
        eyebrow: "Takeaway",
        title: "Every EV needs a reason",
        bullets: ["Represent one modeled pattern", "Distinguish task from nuisance", "Inspect the final design"],
        narrationText: "An EV is one hypothesized source of variation in the design matrix. Define what it represents, distinguish effects of interest from nuisance structure, and inspect its timing and relationship to other columns before interpreting beta estimates or contrasts.",
        sourceRefs: [lecture("L10_Stats-Basic", [15, 16, 17, 18], "GLM columns, contrasts, and nuisance regressors")],
      }),
    ],
  },

  "hrf-and-convolution": {
    description: "Turn event timing into a delayed BOLD predictor by convolving neural-event estimates with a hemodynamic response model.",
    scenes: [
      scene({
        id: "opening",
        kind: "opening",
        layout: "opening",
        eyebrow: "From event to BOLD",
        title: "The blood response arrives late",
        body: "Convolution turns brief event timing into a delayed, smooth model predictor.",
        visual: { type: "hrf-convolution" },
        narrationText: "Neural events are fast, but the BOLD response is delayed and smooth. The hemodynamic response function, or HRF, approximates that response shape. Convolution combines event timing with the HRF to create a predictor that the GLM can compare with measured BOLD signal.",
        sourceRefs: [lecture("L02_PhysicsPhysiology", [40, 41, 42, 43], "BOLD physiology and hemodynamic response"), lecture("L09_ExperimentalDesign", [17, 24, 28], "Timing and hemodynamic estimation")],
      }),
      scene({
        id: "core-idea",
        kind: "explanation",
        layout: "diagram",
        eyebrow: "Convolution",
        title: "Apply the response at every event",
        body: "Overlapping responses add together to form the expected BOLD pattern.",
        visual: { type: "hrf-convolution" },
        narrationText: "Imagine placing a copy of the HRF at every event onset. Each copy is scaled by the event amplitude, shifted in time, and added to the others. The result is a continuous predictor. Closely spaced events produce overlapping responses, which is why timing affects estimation.",
        sourceRefs: [lecture("L09_ExperimentalDesign", [17, 23, 24, 31, 32, 35], "Response overlap and trial spacing")],
      }),
      scene({
        id: "observable-check",
        kind: "practice",
        layout: "diagram",
        eyebrow: "Read the shape",
        title: "Rise, peak, fall, undershoot",
        body: "A canonical HRF is a model of BOLD dynamics, not a measured neural waveform.",
        visual: {
          type: "comparison",
          items: [
            { label: "Rise", value: "~2 s", detail: "Signal begins above baseline.", tone: "blue" },
            { label: "Peak", value: "~5 s", detail: "Canonical response reaches its maximum.", tone: "accent" },
            { label: "Undershoot", value: "later", detail: "Signal may dip below baseline.", tone: "coral" },
          ],
        },
        narrationText: "A canonical response begins rising after roughly two seconds, peaks near five seconds, and may show a later undershoot. Those numbers are useful approximations, not universal constants. The HRF models vascular dynamics associated with neural activity; it is not the neural event itself.",
        sourceRefs: [lecture("L01_IntroMRIsafety", [35], "BOLD temporal resolution"), lecture("L02_PhysicsPhysiology", [43], "Basic hemodynamic response form")],
      }),
      scene({
        id: "quality-control",
        kind: "quality-control",
        layout: "dashboard",
        eyebrow: "Model uncertainty",
        title: "Real HRFs vary",
        body: "Latency and shape differ across people, brain regions, and physiological conditions.",
        visual: {
          type: "comparison",
          items: [
            { label: "Person", detail: "Vascular and physiological differences", tone: "blue" },
            { label: "Region", detail: "Local response latency and shape", tone: "accent" },
            { label: "Design", detail: "Timing changes overlap and identifiability", tone: "coral" },
          ],
        },
        narrationText: "The canonical HRF is a practical model, but real responses vary across participants and regions. Basis functions or finite impulse response models can represent some variation. The appropriate choice depends on the hypothesis, design, and available data.",
        sourceRefs: [lecture("L08_SignalNoisePreprocessing", [23, 24], "Intersubject and intrasubject HRF variability")],
      }),
      scene({
        id: "summary",
        kind: "summary",
        layout: "summary",
        eyebrow: "Takeaway",
        title: "Timing becomes a BOLD prediction",
        bullets: ["Events estimate neural timing", "The HRF models vascular delay", "Convolution builds the predictor"],
        narrationText: "Convolution translates event timing into an expected BOLD pattern by applying the HRF at each event. Read the predictor as a model of delayed vascular response, and keep biological variability and design overlap in mind when interpreting the fit.",
        sourceRefs: [lecture("L02_PhysicsPhysiology", [42, 43], "Neural origins and hemodynamic response"), lecture("L09_ExperimentalDesign", [24, 32, 35], "Response estimation and timing")],
      }),
    ],
  },

  "confound-regressors": {
    description: "Model structured nuisance variation such as motion and drift without pretending that regression can repair every data-quality problem.",
    scenes: [
      scene({
        id: "opening",
        kind: "opening",
        layout: "opening",
        eyebrow: "Separate effects",
        title: "Not every pattern is the task",
        body: "Confound regressors model structured variation that is not the effect of interest.",
        visual: {
          type: "confound-separation",
          items: [
            { label: "Task timing", detail: "hypothesized effect", tone: "accent" },
            { label: "Parametric value", detail: "graded effect", tone: "blue" },
            { label: "Head motion", detail: "nuisance", tone: "coral" },
            { label: "Scanner drift", detail: "nuisance", tone: "muted" },
          ],
        },
        narrationText: "Measured BOLD contains task-related variation and many other patterns. Confound regressors represent structured nuisance variation, such as head motion or slow drift, so the GLM does not attribute all shared change to the task. They reduce some bias; they do not repair every artifact.",
        sourceRefs: [lecture("L08_SignalNoisePreprocessing", [15, 18, 19], "Sources and spatial distribution of noise"), lecture("L10_Stats-Basic", [18], "Task and nuisance regressors")],
      }),
      scene({
        id: "core-idea",
        kind: "explanation",
        layout: "diagram",
        eyebrow: "Shared model, different meaning",
        title: "Task and nuisance columns coexist",
        body: "Each beta is estimated after accounting for the other columns in the design.",
        visual: {
          type: "confound-separation",
          items: [
            { label: "Condition A", detail: "effect of interest", tone: "accent" },
            { label: "Condition B", detail: "effect of interest", tone: "blue" },
            { label: "Motion X", detail: "translation", tone: "coral" },
            { label: "Motion roll", detail: "rotation", tone: "muted" },
          ],
        },
        narrationText: "Task and nuisance regressors enter the same design matrix but support different interpretations. The task columns estimate effects of interest. The nuisance columns absorb specified variation. Because the estimates are conditional, strong dependence between columns can change both precision and interpretation.",
        sourceRefs: [lecture("L10_Stats-Basic", [18, 20], "Task, nuisance, and regressor dependence")],
      }),
      scene({
        id: "observable-check",
        kind: "evidence",
        layout: "evidence",
        eyebrow: "Inspect motion evidence",
        title: "Plots reveal structured movement",
        body: "Look for gradual drift, abrupt displacement, and movement aligned with the task.",
        visual: {
          type: "image-evidence",
          asset: "/curriculum/feat-prestats.png",
          caption: "The FEAT pre-stats report contains motion and preprocessing evidence to inspect before modeling.",
        },
        narrationText: "Motion parameters describe translation and rotation across the run. Inspect the plots for abrupt jumps, slow drift, and patterns synchronized with the task. A motion regressor can reduce linear shared variance, but task-correlated motion is especially difficult to separate.",
        sourceRefs: [repositoryAsset("/curriculum/feat-prestats.png", "Authentic FEAT pre-stats evidence"), lecture("L08_SignalNoisePreprocessing", [45, 46, 47, 48, 49], "Motion effects, correction, and limitations")],
      }),
      scene({
        id: "quality-control",
        kind: "quality-control",
        layout: "dashboard",
        eyebrow: "Regression has limits",
        title: "Confounds cannot restore lost information",
        body: "Missing coverage, severe distortion, spin-history effects, and corrupted volumes may remain unusable.",
        visual: {
          type: "checklist",
          items: [
            { label: "Inspect the images", detail: "Motion estimates do not show every artifact." },
            { label: "Inspect task correlation", detail: "Nuisance and effect columns may be inseparable." },
            { label: "Document exclusions", detail: "Some runs or volumes may not support inference." },
          ],
        },
        narrationText: "Confound regression does not reconstruct missing anatomy or undo every motion artifact. Distortion can depend on position in the magnetic field, and spin-history effects can persist after realignment. Severe problems may require censoring, exclusion, or a revised acquisition—not another regressor.",
        sourceRefs: [lecture("L08_SignalNoisePreprocessing", [46, 47, 48, 49], "Intrinsic limitations of motion correction")],
      }),
      scene({
        id: "summary",
        kind: "summary",
        layout: "summary",
        eyebrow: "Takeaway",
        title: "Model nuisance, inspect damage",
        bullets: ["Separate task and confounds", "Check motion and drift", "Do not overclaim correction"],
        narrationText: "Confound regressors help separate specified nuisance variation from task effects. Inspect the nuisance patterns, their relationship to the task, and the underlying images. A cleaner model does not automatically mean the original data became valid.",
        sourceRefs: [lecture("L08_SignalNoisePreprocessing", [39, 40, 45, 49, 67, 68], "Preprocessing and temporal filtering limits")],
      }),
    ],
  },

  "reviewing-complete-feat-report": {
    description: "Review a completed FEAT report as an ordered chain of preprocessing, registration, design, and inferential evidence.",
    scenes: [
      scene({
        id: "opening",
        kind: "opening",
        layout: "opening",
        eyebrow: "FEAT quality control",
        title: "Results depend on every earlier step",
        body: "Review inputs and transformations before interpreting a statistical map.",
        visual: {
          type: "feat-chain",
          items: [
            { label: "Pre-stats", detail: "motion and preprocessing" },
            { label: "Registration", detail: "spatial correspondence" },
            { label: "Design", detail: "EVs and contrasts" },
            { label: "Inference", detail: "thresholded results" },
          ],
        },
        narrationText: "A completed FEAT report is not automatically a valid analysis. It is a chain of evidence. Review motion and preprocessing first, registration second, the design and contrasts third, and statistical inference last. A failure early in the chain limits every later conclusion.",
        sourceRefs: [lecture("L08_SignalNoisePreprocessing", [39, 40, 41], "Preprocessing sequence"), lecture("L10_Stats-Basic", [26, 40, 42], "Inference, correction, and visualization")],
      }),
      scene({
        id: "review-order",
        kind: "explanation",
        layout: "evidence",
        eyebrow: "Review in order",
        title: "The report is a dependency map",
        body: "Each section answers a different quality-control question.",
        visual: {
          type: "image-evidence",
          asset: "/curriculum/feat-report.png",
          caption: "The FEAT report links preprocessing, registration, design, and statistical output.",
        },
        narrationText: "Begin with pre-stats and ask whether motion, masking, and preprocessing outputs are plausible. Continue to registration and inspect anatomical correspondence. Then examine the design matrix, EVs, and contrasts. Only after those dependencies pass should you interpret thresholded results.",
        sourceRefs: [repositoryAsset("/curriculum/feat-report.png", "Authentic FEAT report"), lecture("L08_SignalNoisePreprocessing", [40, 42, 45, 54, 58], "Preprocessing and registration checks")],
      }),
      scene({
        id: "three-questions",
        kind: "evidence",
        layout: "evidence",
        eyebrow: "Write what you checked",
        title: "Specific observations are auditable",
        body: "Replace “looks fine” with evidence about motion, boundaries, timing, and contrast direction.",
        visual: {
          type: "image-evidence",
          asset: "/curriculum/feat-registration.png",
          caption: "Registration should be evaluated across multiple slices and anatomical boundaries.",
        },
        narrationText: "For motion, describe the pattern and any abrupt displacement. For registration, name boundaries and locations that agree or fail. For design, match columns to timing files and contrast weights to the hypothesis. Specific observations can be reviewed; vague reassurance cannot.",
        sourceRefs: [repositoryAsset("/curriculum/feat-registration.png", "Authentic FEAT registration evidence"), lecture("L08_SignalNoisePreprocessing", [45, 47, 49, 54, 58, 59, 60], "Motion and registration limitations")],
      }),
      scene({
        id: "results-last",
        kind: "quality-control",
        layout: "dashboard",
        eyebrow: "Results come last",
        title: "A z-statistic is not an effect size",
        body: "Keep estimated effect, uncertainty, standardized evidence, and thresholded display distinct.",
        visual: {
          type: "comparison",
          items: [
            { label: "cope", value: "Effect", detail: "Estimated contrast of beta values.", tone: "blue" },
            { label: "varcope", value: "Uncertainty", detail: "Estimated variance of the contrast.", tone: "accent" },
            { label: "z-stat", value: "Evidence", detail: "Standardized statistic, not effect magnitude.", tone: "coral" },
          ],
        },
        narrationText: "A cope is the estimated contrast effect. A varcope describes uncertainty in that estimate. A t or z statistic standardizes evidence relative to uncertainty. A thresholded map shows locations surviving the chosen inferential procedure. Do not describe a z-statistic map as an effect-size map.",
        sourceRefs: [lecture("L10_Stats-Basic", [26, 27, 28, 30, 32, 33, 34, 40], "Multiple comparisons and inferential displays")],
      }),
      scene({
        id: "summary",
        kind: "summary",
        layout: "summary",
        eyebrow: "Document the decision",
        title: "Pass, concern, or fail—with evidence",
        bullets: ["Name what you reviewed", "Record likely impact", "Link claims to the analysis plan"],
        narrationText: "Finish with an explicit quality-control judgment: pass, concern, or fail, followed by the observations that support it. Record limitations and their likely effect on interpretation. The goal is not to prove that FEAT finished; it is to decide what this run can defensibly support.",
        sourceRefs: [lecture("L10_Stats-Basic", [45, 46, 47], "Reverse inference and interpretation complexity"), lecture("L12_EthicalIssues", [21, 22, 23], "Reverse inference, circularity, and analytic flexibility")],
      }),
    ],
  },
};
